//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.ClientPRDSupplier {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SupplierViewOption", Namespace="http://Compano.com/Modules/PRD")]
    public enum SupplierViewOption : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Supplier = 0,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FilterElement", Namespace="http://Compano.com/Modules/PRD")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientPRDSupplier.SupplierViewOption))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientPRDSupplier.FilterElement[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientPRDSupplier.ConditionTypeOption))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientPRDSupplier.SupplierXmlField[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientPRDSupplier.SupplierXmlField))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientPRDSupplier.SupplierFilterField[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientPRDSupplier.SupplierFilterField))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientPRDSupplier.ArrayOfString))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientPRDSupplier.Facet))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientPRDSupplier.FacetItem[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientPRDSupplier.FacetItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientPRDSupplier.Facet[]))]
    public partial class FilterElement : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Demo.ClientPRDSupplier.ConditionTypeOption ConditionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FieldNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object Value1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object Value2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Demo.ClientPRDSupplier.ConditionTypeOption ConditionType {
            get {
                return this.ConditionTypeField;
            }
            set {
                if ((this.ConditionTypeField.Equals(value) != true)) {
                    this.ConditionTypeField = value;
                    this.RaisePropertyChanged("ConditionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FieldName {
            get {
                return this.FieldNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldNameField, value) != true)) {
                    this.FieldNameField = value;
                    this.RaisePropertyChanged("FieldName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public object Value1 {
            get {
                return this.Value1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Value1Field, value) != true)) {
                    this.Value1Field = value;
                    this.RaisePropertyChanged("Value1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public object Value2 {
            get {
                return this.Value2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Value2Field, value) != true)) {
                    this.Value2Field = value;
                    this.RaisePropertyChanged("Value2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConditionTypeOption", Namespace="http://Compano.com/Modules/PRD")]
    public enum ConditionTypeOption : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Equals = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EqualsField = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GreaterThan = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GreaterThanField = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GreaterThanOrEquals = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GreaterThanOrEqualsField = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LesserThan = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LesserThanField = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LesserThanOrEquals = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LesserThanOrEqualsField = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Between = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Outside = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Contains = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotContains = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EqualsNoCase = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ItemInSet = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        StartsWith = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EndsWith = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InRange = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotNull = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Null = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HasChilds = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HasNoChilds = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InAudience = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Approximately = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ApproximatelyField = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InRangeField = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LastWeek = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LastMonth = 28,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NextWeek = 29,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NextMonth = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotEquals = 31,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotEqualsField = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ItemNotInSet = 33,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HasUnarchivedChilds = 34,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HasNoUnarchivedChilds = 35,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        All = 36,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SupplierXmlField", Namespace="http://Compano.com/Modules/PRD")]
    public enum SupplierXmlField : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ConstantNow = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ConstantText = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ConstantToday = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GLNCode = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GlnIcc = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GlnIccUser = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GlnIcf = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GlnIcfUser = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ICMUserName = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IsDefault = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Logo = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrderEmail = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactCreditor = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactCreditorBankAccountNo = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactCreditorBIC = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactCreditorCreditSqueeze = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactCreditorDebtorNumber = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactCreditorFormattedIBAN = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactCreditorIBAN = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactCreditorIsCreditSqueezeExVAT = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactCreditorIsDefaultVATTransfer = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactCreditorNo = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactCreditorPaymentMethod = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactCreditorPaymentTerm = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactEmail = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactFaxNo = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactGoogleMap = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactLongName = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactMobileNo = 28,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactNo = 29,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactPostalAddressBlock = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactPostalAddressCity = 31,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactPostalAddressCountryCode = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactPostalAddressCountryDescription = 33,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactPostalAddressHouseNumber = 34,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactPostalAddressProvince = 35,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactPostalAddressStreet = 36,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactPostalAddressStreetAndHouseNumber = 37,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactPostalAddressZipCode = 38,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactPostalAddressZipCodeAndCity = 39,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactTelNo = 40,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactVisitingAddressBlock = 41,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactVisitingAddressCity = 42,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactVisitingAddressCountryCode = 43,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactVisitingAddressCountryDescription = 44,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactVisitingAddressHouseNumber = 45,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactVisitingAddressLine = 46,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactVisitingAddressProvince = 47,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactVisitingAddressStreet = 48,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactVisitingAddressStreetAndHouseNumber = 49,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactVisitingAddressZipCode = 50,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactVisitingAddressZipCodeAndCity = 51,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationLogo = 52,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationName = 53,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationName2 = 54,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationOfficesXml = 55,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationShortName = 56,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationWeb = 57,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SalesOrganizationArchivedDateTime = 58,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SalesOrganizationCode = 59,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SalesOrganizationShortDescription = 60,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SendType = 61,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SupplierFilterField", Namespace="http://Compano.com/Modules/PRD")]
    public enum SupplierFilterField : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ConstantNow = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ConstantToday = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GLNCode = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GlnIcc = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GlnIccUser = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GlnIcf = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GlnIcfUser = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ICMUserName = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IsDefault = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Members = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrderEmail = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Organization = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactCreditor = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactCreditorBankAccountNo = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactCreditorBIC = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactCreditorCreditSqueeze = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactCreditorDebtorNumber = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactCreditorFormattedIBAN = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactCreditorIBAN = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactCreditorIsCreditSqueezeExVAT = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactCreditorIsDefaultVATTransfer = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactCreditorNo = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactCreditorPaymentMethod = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactCreditorPaymentTerm = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactEmail = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactLongName = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactNo = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactPostalAddressCity = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactPostalAddressCountryCode = 28,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactPostalAddressCountryDescription = 29,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactPostalAddressHouseNumber = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactPostalAddressProvince = 31,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactPostalAddressStreet = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactPostalAddressZipCode = 33,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactVisitingAddressCity = 34,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactVisitingAddressCountryCode = 35,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactVisitingAddressCountryDescription = 36,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactVisitingAddressHouseNumber = 37,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactVisitingAddressProvince = 38,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactVisitingAddressStreet = 39,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationContactVisitingAddressZipCode = 40,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationName = 41,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationName2 = 42,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationShortName = 43,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PurchaseOrders = 44,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SalesOrganization = 45,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SalesOrganizationArchivedDateTime = 46,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SalesOrganizationCode = 47,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SalesOrganizationShortDescription = 48,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SendType = 49,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://Compano.com/Modules/PRD", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Facet", Namespace="http://Compano.com/Modules/PRD")]
    [System.SerializableAttribute()]
    public partial class Facet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        private bool IsSelectedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Demo.ClientPRDSupplier.FacetItem[] ItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Demo.ClientPRDSupplier.FacetItem SelectedItemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool IsSelected {
            get {
                return this.IsSelectedField;
            }
            set {
                if ((this.IsSelectedField.Equals(value) != true)) {
                    this.IsSelectedField = value;
                    this.RaisePropertyChanged("IsSelected");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Demo.ClientPRDSupplier.FacetItem[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Demo.ClientPRDSupplier.FacetItem SelectedItem {
            get {
                return this.SelectedItemField;
            }
            set {
                if ((object.ReferenceEquals(this.SelectedItemField, value) != true)) {
                    this.SelectedItemField = value;
                    this.RaisePropertyChanged("SelectedItem");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FacetItem", Namespace="http://Compano.com/Modules/PRD")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientPRDSupplier.SupplierViewOption))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientPRDSupplier.FilterElement[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientPRDSupplier.FilterElement))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientPRDSupplier.ConditionTypeOption))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientPRDSupplier.SupplierXmlField[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientPRDSupplier.SupplierXmlField))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientPRDSupplier.SupplierFilterField[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientPRDSupplier.SupplierFilterField))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientPRDSupplier.ArrayOfString))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientPRDSupplier.Facet))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientPRDSupplier.FacetItem[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientPRDSupplier.Facet[]))]
    public partial class FacetItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        private int RecordCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object KeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RecordCount {
            get {
                return this.RecordCountField;
            }
            set {
                if ((this.RecordCountField.Equals(value) != true)) {
                    this.RecordCountField = value;
                    this.RaisePropertyChanged("RecordCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Unit {
            get {
                return this.UnitField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitField, value) != true)) {
                    this.UnitField = value;
                    this.RaisePropertyChanged("Unit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public object Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Compano.com/Modules/PRD", ConfigurationName="ClientPRDSupplier.SupplierServiceSoap")]
    public interface SupplierServiceSoap {
        
        // CODEGEN: Generating message contract since element name sessionHandle from namespace http://Compano.com/Modules/PRD is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Compano.com/Modules/PRD/SetDefaultView", ReplyAction="*")]
        Demo.ClientPRDSupplier.SetDefaultViewResponse SetDefaultView(Demo.ClientPRDSupplier.SetDefaultViewRequest request);
        
        // CODEGEN: Generating message contract since element name sessionHandle from namespace http://Compano.com/Modules/PRD is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Compano.com/Modules/PRD/SelectAsJSON", ReplyAction="*")]
        Demo.ClientPRDSupplier.SelectAsJSONResponse SelectAsJSON(Demo.ClientPRDSupplier.SelectAsJSONRequest request);
        
        // CODEGEN: Generating message contract since element name sessionHandle from namespace http://Compano.com/Modules/PRD is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Compano.com/Modules/PRD/Select", ReplyAction="*")]
        Demo.ClientPRDSupplier.SelectResponse Select(Demo.ClientPRDSupplier.SelectRequest request);
        
        // CODEGEN: Generating message contract since element name sessionHandle from namespace http://Compano.com/Modules/PRD is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Compano.com/Modules/PRD/GetGridUrl", ReplyAction="*")]
        Demo.ClientPRDSupplier.GetGridUrlResponse GetGridUrl(Demo.ClientPRDSupplier.GetGridUrlRequest request);
        
        // CODEGEN: Generating message contract since element name sessionHandle from namespace http://Compano.com/Modules/PRD is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Compano.com/Modules/PRD/GetViewAsXml", ReplyAction="*")]
        Demo.ClientPRDSupplier.GetViewAsXmlResponse GetViewAsXml(Demo.ClientPRDSupplier.GetViewAsXmlRequest request);
        
        // CODEGEN: Generating message contract since element name sessionHandle from namespace http://Compano.com/Modules/PRD is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Compano.com/Modules/PRD/SetViewFilter", ReplyAction="*")]
        Demo.ClientPRDSupplier.SetViewFilterResponse SetViewFilter(Demo.ClientPRDSupplier.SetViewFilterRequest request);
        
        // CODEGEN: Generating message contract since element name sessionHandle from namespace http://Compano.com/Modules/PRD is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Compano.com/Modules/PRD/SetViewSortOrder", ReplyAction="*")]
        Demo.ClientPRDSupplier.SetViewSortOrderResponse SetViewSortOrder(Demo.ClientPRDSupplier.SetViewSortOrderRequest request);
        
        // CODEGEN: Generating message contract since element name sessionHandle from namespace http://Compano.com/Modules/PRD is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Compano.com/Modules/PRD/GetViewCount", ReplyAction="*")]
        Demo.ClientPRDSupplier.GetViewCountResponse GetViewCount(Demo.ClientPRDSupplier.GetViewCountRequest request);
        
        // CODEGEN: Generating message contract since element name sessionHandle from namespace http://Compano.com/Modules/PRD is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Compano.com/Modules/PRD/ResetViewFilter", ReplyAction="*")]
        Demo.ClientPRDSupplier.ResetViewFilterResponse ResetViewFilter(Demo.ClientPRDSupplier.ResetViewFilterRequest request);
        
        // CODEGEN: Generating message contract since element name sessionHandle from namespace http://Compano.com/Modules/PRD is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Compano.com/Modules/PRD/SetViewAdvancedFilter", ReplyAction="*")]
        Demo.ClientPRDSupplier.SetViewAdvancedFilterResponse SetViewAdvancedFilter(Demo.ClientPRDSupplier.SetViewAdvancedFilterRequest request);
        
        // CODEGEN: Generating message contract since element name sessionHandle from namespace http://Compano.com/Modules/PRD is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Compano.com/Modules/PRD/SetViewSearchText", ReplyAction="*")]
        Demo.ClientPRDSupplier.SetViewSearchTextResponse SetViewSearchText(Demo.ClientPRDSupplier.SetViewSearchTextRequest request);
        
        // CODEGEN: Generating message contract since element name sessionHandle from namespace http://Compano.com/Modules/PRD is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Compano.com/Modules/PRD/SetViewFacet", ReplyAction="*")]
        Demo.ClientPRDSupplier.SetViewFacetResponse SetViewFacet(Demo.ClientPRDSupplier.SetViewFacetRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetDefaultViewRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetDefaultView", Namespace="http://Compano.com/Modules/PRD", Order=0)]
        public Demo.ClientPRDSupplier.SetDefaultViewRequestBody Body;
        
        public SetDefaultViewRequest() {
        }
        
        public SetDefaultViewRequest(Demo.ClientPRDSupplier.SetDefaultViewRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/PRD")]
    public partial class SetDefaultViewRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionHandle;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public Demo.ClientPRDSupplier.SupplierViewOption view;
        
        public SetDefaultViewRequestBody() {
        }
        
        public SetDefaultViewRequestBody(string sessionHandle, Demo.ClientPRDSupplier.SupplierViewOption view) {
            this.sessionHandle = sessionHandle;
            this.view = view;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetDefaultViewResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetDefaultViewResponse", Namespace="http://Compano.com/Modules/PRD", Order=0)]
        public Demo.ClientPRDSupplier.SetDefaultViewResponseBody Body;
        
        public SetDefaultViewResponse() {
        }
        
        public SetDefaultViewResponse(Demo.ClientPRDSupplier.SetDefaultViewResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/PRD")]
    public partial class SetDefaultViewResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SetDefaultViewResult;
        
        public SetDefaultViewResponseBody() {
        }
        
        public SetDefaultViewResponseBody(string SetDefaultViewResult) {
            this.SetDefaultViewResult = SetDefaultViewResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAsJSONRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectAsJSON", Namespace="http://Compano.com/Modules/PRD", Order=0)]
        public Demo.ClientPRDSupplier.SelectAsJSONRequestBody Body;
        
        public SelectAsJSONRequest() {
        }
        
        public SelectAsJSONRequest(Demo.ClientPRDSupplier.SelectAsJSONRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/PRD")]
    public partial class SelectAsJSONRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionHandle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Demo.ClientPRDSupplier.FilterElement[] filterElements;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Demo.ClientPRDSupplier.SupplierXmlField[] fields;
        
        public SelectAsJSONRequestBody() {
        }
        
        public SelectAsJSONRequestBody(string sessionHandle, Demo.ClientPRDSupplier.FilterElement[] filterElements, Demo.ClientPRDSupplier.SupplierXmlField[] fields) {
            this.sessionHandle = sessionHandle;
            this.filterElements = filterElements;
            this.fields = fields;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAsJSONResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectAsJSONResponse", Namespace="http://Compano.com/Modules/PRD", Order=0)]
        public Demo.ClientPRDSupplier.SelectAsJSONResponseBody Body;
        
        public SelectAsJSONResponse() {
        }
        
        public SelectAsJSONResponse(Demo.ClientPRDSupplier.SelectAsJSONResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/PRD")]
    public partial class SelectAsJSONResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SelectAsJSONResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string json;
        
        public SelectAsJSONResponseBody() {
        }
        
        public SelectAsJSONResponseBody(string SelectAsJSONResult, string json) {
            this.SelectAsJSONResult = SelectAsJSONResult;
            this.json = json;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Select", Namespace="http://Compano.com/Modules/PRD", Order=0)]
        public Demo.ClientPRDSupplier.SelectRequestBody Body;
        
        public SelectRequest() {
        }
        
        public SelectRequest(Demo.ClientPRDSupplier.SelectRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/PRD")]
    public partial class SelectRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionHandle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Demo.ClientPRDSupplier.SupplierFilterField[] filterFields;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Demo.ClientPRDSupplier.ArrayOfString filterValues;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string searchText;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public Demo.ClientPRDSupplier.SupplierXmlField[] fields;
        
        public SelectRequestBody() {
        }
        
        public SelectRequestBody(string sessionHandle, Demo.ClientPRDSupplier.SupplierFilterField[] filterFields, Demo.ClientPRDSupplier.ArrayOfString filterValues, string searchText, Demo.ClientPRDSupplier.SupplierXmlField[] fields) {
            this.sessionHandle = sessionHandle;
            this.filterFields = filterFields;
            this.filterValues = filterValues;
            this.searchText = searchText;
            this.fields = fields;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectResponse", Namespace="http://Compano.com/Modules/PRD", Order=0)]
        public Demo.ClientPRDSupplier.SelectResponseBody Body;
        
        public SelectResponse() {
        }
        
        public SelectResponse(Demo.ClientPRDSupplier.SelectResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/PRD")]
    public partial class SelectResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SelectResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string xml;
        
        public SelectResponseBody() {
        }
        
        public SelectResponseBody(string SelectResult, string xml) {
            this.SelectResult = SelectResult;
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGridUrlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGridUrl", Namespace="http://Compano.com/Modules/PRD", Order=0)]
        public Demo.ClientPRDSupplier.GetGridUrlRequestBody Body;
        
        public GetGridUrlRequest() {
        }
        
        public GetGridUrlRequest(Demo.ClientPRDSupplier.GetGridUrlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/PRD")]
    public partial class GetGridUrlRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionHandle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Demo.ClientPRDSupplier.SupplierFilterField[] filterFields;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Demo.ClientPRDSupplier.ArrayOfString filterValues;
        
        public GetGridUrlRequestBody() {
        }
        
        public GetGridUrlRequestBody(string sessionHandle, Demo.ClientPRDSupplier.SupplierFilterField[] filterFields, Demo.ClientPRDSupplier.ArrayOfString filterValues) {
            this.sessionHandle = sessionHandle;
            this.filterFields = filterFields;
            this.filterValues = filterValues;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGridUrlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGridUrlResponse", Namespace="http://Compano.com/Modules/PRD", Order=0)]
        public Demo.ClientPRDSupplier.GetGridUrlResponseBody Body;
        
        public GetGridUrlResponse() {
        }
        
        public GetGridUrlResponse(Demo.ClientPRDSupplier.GetGridUrlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/PRD")]
    public partial class GetGridUrlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetGridUrlResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string url;
        
        public GetGridUrlResponseBody() {
        }
        
        public GetGridUrlResponseBody(string GetGridUrlResult, string url) {
            this.GetGridUrlResult = GetGridUrlResult;
            this.url = url;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetViewAsXmlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetViewAsXml", Namespace="http://Compano.com/Modules/PRD", Order=0)]
        public Demo.ClientPRDSupplier.GetViewAsXmlRequestBody Body;
        
        public GetViewAsXmlRequest() {
        }
        
        public GetViewAsXmlRequest(Demo.ClientPRDSupplier.GetViewAsXmlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/PRD")]
    public partial class GetViewAsXmlRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionHandle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Demo.ClientPRDSupplier.SupplierXmlField[] fields;
        
        public GetViewAsXmlRequestBody() {
        }
        
        public GetViewAsXmlRequestBody(string sessionHandle, Demo.ClientPRDSupplier.SupplierXmlField[] fields) {
            this.sessionHandle = sessionHandle;
            this.fields = fields;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetViewAsXmlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetViewAsXmlResponse", Namespace="http://Compano.com/Modules/PRD", Order=0)]
        public Demo.ClientPRDSupplier.GetViewAsXmlResponseBody Body;
        
        public GetViewAsXmlResponse() {
        }
        
        public GetViewAsXmlResponse(Demo.ClientPRDSupplier.GetViewAsXmlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/PRD")]
    public partial class GetViewAsXmlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetViewAsXmlResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string xml;
        
        public GetViewAsXmlResponseBody() {
        }
        
        public GetViewAsXmlResponseBody(string GetViewAsXmlResult, string xml) {
            this.GetViewAsXmlResult = GetViewAsXmlResult;
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetViewFilterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetViewFilter", Namespace="http://Compano.com/Modules/PRD", Order=0)]
        public Demo.ClientPRDSupplier.SetViewFilterRequestBody Body;
        
        public SetViewFilterRequest() {
        }
        
        public SetViewFilterRequest(Demo.ClientPRDSupplier.SetViewFilterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/PRD")]
    public partial class SetViewFilterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionHandle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Demo.ClientPRDSupplier.SupplierFilterField[] filterFields;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Demo.ClientPRDSupplier.ArrayOfString filterValues;
        
        public SetViewFilterRequestBody() {
        }
        
        public SetViewFilterRequestBody(string sessionHandle, Demo.ClientPRDSupplier.SupplierFilterField[] filterFields, Demo.ClientPRDSupplier.ArrayOfString filterValues) {
            this.sessionHandle = sessionHandle;
            this.filterFields = filterFields;
            this.filterValues = filterValues;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetViewFilterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetViewFilterResponse", Namespace="http://Compano.com/Modules/PRD", Order=0)]
        public Demo.ClientPRDSupplier.SetViewFilterResponseBody Body;
        
        public SetViewFilterResponse() {
        }
        
        public SetViewFilterResponse(Demo.ClientPRDSupplier.SetViewFilterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/PRD")]
    public partial class SetViewFilterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SetViewFilterResult;
        
        public SetViewFilterResponseBody() {
        }
        
        public SetViewFilterResponseBody(string SetViewFilterResult) {
            this.SetViewFilterResult = SetViewFilterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetViewSortOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetViewSortOrder", Namespace="http://Compano.com/Modules/PRD", Order=0)]
        public Demo.ClientPRDSupplier.SetViewSortOrderRequestBody Body;
        
        public SetViewSortOrderRequest() {
        }
        
        public SetViewSortOrderRequest(Demo.ClientPRDSupplier.SetViewSortOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/PRD")]
    public partial class SetViewSortOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionHandle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sortExpression;
        
        public SetViewSortOrderRequestBody() {
        }
        
        public SetViewSortOrderRequestBody(string sessionHandle, string sortExpression) {
            this.sessionHandle = sessionHandle;
            this.sortExpression = sortExpression;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetViewSortOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetViewSortOrderResponse", Namespace="http://Compano.com/Modules/PRD", Order=0)]
        public Demo.ClientPRDSupplier.SetViewSortOrderResponseBody Body;
        
        public SetViewSortOrderResponse() {
        }
        
        public SetViewSortOrderResponse(Demo.ClientPRDSupplier.SetViewSortOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/PRD")]
    public partial class SetViewSortOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SetViewSortOrderResult;
        
        public SetViewSortOrderResponseBody() {
        }
        
        public SetViewSortOrderResponseBody(string SetViewSortOrderResult) {
            this.SetViewSortOrderResult = SetViewSortOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetViewCountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetViewCount", Namespace="http://Compano.com/Modules/PRD", Order=0)]
        public Demo.ClientPRDSupplier.GetViewCountRequestBody Body;
        
        public GetViewCountRequest() {
        }
        
        public GetViewCountRequest(Demo.ClientPRDSupplier.GetViewCountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/PRD")]
    public partial class GetViewCountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionHandle;
        
        public GetViewCountRequestBody() {
        }
        
        public GetViewCountRequestBody(string sessionHandle) {
            this.sessionHandle = sessionHandle;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetViewCountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetViewCountResponse", Namespace="http://Compano.com/Modules/PRD", Order=0)]
        public Demo.ClientPRDSupplier.GetViewCountResponseBody Body;
        
        public GetViewCountResponse() {
        }
        
        public GetViewCountResponse(Demo.ClientPRDSupplier.GetViewCountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/PRD")]
    public partial class GetViewCountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetViewCountResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int recordCount;
        
        public GetViewCountResponseBody() {
        }
        
        public GetViewCountResponseBody(string GetViewCountResult, int recordCount) {
            this.GetViewCountResult = GetViewCountResult;
            this.recordCount = recordCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResetViewFilterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResetViewFilter", Namespace="http://Compano.com/Modules/PRD", Order=0)]
        public Demo.ClientPRDSupplier.ResetViewFilterRequestBody Body;
        
        public ResetViewFilterRequest() {
        }
        
        public ResetViewFilterRequest(Demo.ClientPRDSupplier.ResetViewFilterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/PRD")]
    public partial class ResetViewFilterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionHandle;
        
        public ResetViewFilterRequestBody() {
        }
        
        public ResetViewFilterRequestBody(string sessionHandle) {
            this.sessionHandle = sessionHandle;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResetViewFilterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResetViewFilterResponse", Namespace="http://Compano.com/Modules/PRD", Order=0)]
        public Demo.ClientPRDSupplier.ResetViewFilterResponseBody Body;
        
        public ResetViewFilterResponse() {
        }
        
        public ResetViewFilterResponse(Demo.ClientPRDSupplier.ResetViewFilterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/PRD")]
    public partial class ResetViewFilterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ResetViewFilterResult;
        
        public ResetViewFilterResponseBody() {
        }
        
        public ResetViewFilterResponseBody(string ResetViewFilterResult) {
            this.ResetViewFilterResult = ResetViewFilterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetViewAdvancedFilterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetViewAdvancedFilter", Namespace="http://Compano.com/Modules/PRD", Order=0)]
        public Demo.ClientPRDSupplier.SetViewAdvancedFilterRequestBody Body;
        
        public SetViewAdvancedFilterRequest() {
        }
        
        public SetViewAdvancedFilterRequest(Demo.ClientPRDSupplier.SetViewAdvancedFilterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/PRD")]
    public partial class SetViewAdvancedFilterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionHandle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Demo.ClientPRDSupplier.FilterElement[] filterElements;
        
        public SetViewAdvancedFilterRequestBody() {
        }
        
        public SetViewAdvancedFilterRequestBody(string sessionHandle, Demo.ClientPRDSupplier.FilterElement[] filterElements) {
            this.sessionHandle = sessionHandle;
            this.filterElements = filterElements;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetViewAdvancedFilterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetViewAdvancedFilterResponse", Namespace="http://Compano.com/Modules/PRD", Order=0)]
        public Demo.ClientPRDSupplier.SetViewAdvancedFilterResponseBody Body;
        
        public SetViewAdvancedFilterResponse() {
        }
        
        public SetViewAdvancedFilterResponse(Demo.ClientPRDSupplier.SetViewAdvancedFilterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/PRD")]
    public partial class SetViewAdvancedFilterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SetViewAdvancedFilterResult;
        
        public SetViewAdvancedFilterResponseBody() {
        }
        
        public SetViewAdvancedFilterResponseBody(string SetViewAdvancedFilterResult) {
            this.SetViewAdvancedFilterResult = SetViewAdvancedFilterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetViewSearchTextRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetViewSearchText", Namespace="http://Compano.com/Modules/PRD", Order=0)]
        public Demo.ClientPRDSupplier.SetViewSearchTextRequestBody Body;
        
        public SetViewSearchTextRequest() {
        }
        
        public SetViewSearchTextRequest(Demo.ClientPRDSupplier.SetViewSearchTextRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/PRD")]
    public partial class SetViewSearchTextRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionHandle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string searchText;
        
        public SetViewSearchTextRequestBody() {
        }
        
        public SetViewSearchTextRequestBody(string sessionHandle, string searchText) {
            this.sessionHandle = sessionHandle;
            this.searchText = searchText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetViewSearchTextResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetViewSearchTextResponse", Namespace="http://Compano.com/Modules/PRD", Order=0)]
        public Demo.ClientPRDSupplier.SetViewSearchTextResponseBody Body;
        
        public SetViewSearchTextResponse() {
        }
        
        public SetViewSearchTextResponse(Demo.ClientPRDSupplier.SetViewSearchTextResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/PRD")]
    public partial class SetViewSearchTextResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SetViewSearchTextResult;
        
        public SetViewSearchTextResponseBody() {
        }
        
        public SetViewSearchTextResponseBody(string SetViewSearchTextResult) {
            this.SetViewSearchTextResult = SetViewSearchTextResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetViewFacetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetViewFacet", Namespace="http://Compano.com/Modules/PRD", Order=0)]
        public Demo.ClientPRDSupplier.SetViewFacetRequestBody Body;
        
        public SetViewFacetRequest() {
        }
        
        public SetViewFacetRequest(Demo.ClientPRDSupplier.SetViewFacetRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/PRD")]
    public partial class SetViewFacetRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionHandle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string selectedFacetItem;
        
        public SetViewFacetRequestBody() {
        }
        
        public SetViewFacetRequestBody(string sessionHandle, string selectedFacetItem) {
            this.sessionHandle = sessionHandle;
            this.selectedFacetItem = selectedFacetItem;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetViewFacetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetViewFacetResponse", Namespace="http://Compano.com/Modules/PRD", Order=0)]
        public Demo.ClientPRDSupplier.SetViewFacetResponseBody Body;
        
        public SetViewFacetResponse() {
        }
        
        public SetViewFacetResponse(Demo.ClientPRDSupplier.SetViewFacetResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/PRD")]
    public partial class SetViewFacetResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SetViewFacetResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Demo.ClientPRDSupplier.Facet[] facets;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int recordCount;
        
        public SetViewFacetResponseBody() {
        }
        
        public SetViewFacetResponseBody(string SetViewFacetResult, Demo.ClientPRDSupplier.Facet[] facets, int recordCount) {
            this.SetViewFacetResult = SetViewFacetResult;
            this.facets = facets;
            this.recordCount = recordCount;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SupplierServiceSoapChannel : Demo.ClientPRDSupplier.SupplierServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SupplierServiceSoapClient : System.ServiceModel.ClientBase<Demo.ClientPRDSupplier.SupplierServiceSoap>, Demo.ClientPRDSupplier.SupplierServiceSoap {
        
        public SupplierServiceSoapClient() {
        }
        
        public SupplierServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SupplierServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SupplierServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SupplierServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.ClientPRDSupplier.SetDefaultViewResponse Demo.ClientPRDSupplier.SupplierServiceSoap.SetDefaultView(Demo.ClientPRDSupplier.SetDefaultViewRequest request) {
            return base.Channel.SetDefaultView(request);
        }
        
        public string SetDefaultView(string sessionHandle, Demo.ClientPRDSupplier.SupplierViewOption view) {
            Demo.ClientPRDSupplier.SetDefaultViewRequest inValue = new Demo.ClientPRDSupplier.SetDefaultViewRequest();
            inValue.Body = new Demo.ClientPRDSupplier.SetDefaultViewRequestBody();
            inValue.Body.sessionHandle = sessionHandle;
            inValue.Body.view = view;
            Demo.ClientPRDSupplier.SetDefaultViewResponse retVal = ((Demo.ClientPRDSupplier.SupplierServiceSoap)(this)).SetDefaultView(inValue);
            return retVal.Body.SetDefaultViewResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.ClientPRDSupplier.SelectAsJSONResponse Demo.ClientPRDSupplier.SupplierServiceSoap.SelectAsJSON(Demo.ClientPRDSupplier.SelectAsJSONRequest request) {
            return base.Channel.SelectAsJSON(request);
        }
        
        public string SelectAsJSON(string sessionHandle, Demo.ClientPRDSupplier.FilterElement[] filterElements, Demo.ClientPRDSupplier.SupplierXmlField[] fields, out string json) {
            Demo.ClientPRDSupplier.SelectAsJSONRequest inValue = new Demo.ClientPRDSupplier.SelectAsJSONRequest();
            inValue.Body = new Demo.ClientPRDSupplier.SelectAsJSONRequestBody();
            inValue.Body.sessionHandle = sessionHandle;
            inValue.Body.filterElements = filterElements;
            inValue.Body.fields = fields;
            Demo.ClientPRDSupplier.SelectAsJSONResponse retVal = ((Demo.ClientPRDSupplier.SupplierServiceSoap)(this)).SelectAsJSON(inValue);
            json = retVal.Body.json;
            return retVal.Body.SelectAsJSONResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.ClientPRDSupplier.SelectResponse Demo.ClientPRDSupplier.SupplierServiceSoap.Select(Demo.ClientPRDSupplier.SelectRequest request) {
            return base.Channel.Select(request);
        }
        
        public string Select(string sessionHandle, Demo.ClientPRDSupplier.SupplierFilterField[] filterFields, Demo.ClientPRDSupplier.ArrayOfString filterValues, string searchText, Demo.ClientPRDSupplier.SupplierXmlField[] fields, out string xml) {
            Demo.ClientPRDSupplier.SelectRequest inValue = new Demo.ClientPRDSupplier.SelectRequest();
            inValue.Body = new Demo.ClientPRDSupplier.SelectRequestBody();
            inValue.Body.sessionHandle = sessionHandle;
            inValue.Body.filterFields = filterFields;
            inValue.Body.filterValues = filterValues;
            inValue.Body.searchText = searchText;
            inValue.Body.fields = fields;
            Demo.ClientPRDSupplier.SelectResponse retVal = ((Demo.ClientPRDSupplier.SupplierServiceSoap)(this)).Select(inValue);
            xml = retVal.Body.xml;
            return retVal.Body.SelectResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.ClientPRDSupplier.GetGridUrlResponse Demo.ClientPRDSupplier.SupplierServiceSoap.GetGridUrl(Demo.ClientPRDSupplier.GetGridUrlRequest request) {
            return base.Channel.GetGridUrl(request);
        }
        
        public string GetGridUrl(string sessionHandle, Demo.ClientPRDSupplier.SupplierFilterField[] filterFields, Demo.ClientPRDSupplier.ArrayOfString filterValues, out string url) {
            Demo.ClientPRDSupplier.GetGridUrlRequest inValue = new Demo.ClientPRDSupplier.GetGridUrlRequest();
            inValue.Body = new Demo.ClientPRDSupplier.GetGridUrlRequestBody();
            inValue.Body.sessionHandle = sessionHandle;
            inValue.Body.filterFields = filterFields;
            inValue.Body.filterValues = filterValues;
            Demo.ClientPRDSupplier.GetGridUrlResponse retVal = ((Demo.ClientPRDSupplier.SupplierServiceSoap)(this)).GetGridUrl(inValue);
            url = retVal.Body.url;
            return retVal.Body.GetGridUrlResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.ClientPRDSupplier.GetViewAsXmlResponse Demo.ClientPRDSupplier.SupplierServiceSoap.GetViewAsXml(Demo.ClientPRDSupplier.GetViewAsXmlRequest request) {
            return base.Channel.GetViewAsXml(request);
        }
        
        public string GetViewAsXml(string sessionHandle, Demo.ClientPRDSupplier.SupplierXmlField[] fields, out string xml) {
            Demo.ClientPRDSupplier.GetViewAsXmlRequest inValue = new Demo.ClientPRDSupplier.GetViewAsXmlRequest();
            inValue.Body = new Demo.ClientPRDSupplier.GetViewAsXmlRequestBody();
            inValue.Body.sessionHandle = sessionHandle;
            inValue.Body.fields = fields;
            Demo.ClientPRDSupplier.GetViewAsXmlResponse retVal = ((Demo.ClientPRDSupplier.SupplierServiceSoap)(this)).GetViewAsXml(inValue);
            xml = retVal.Body.xml;
            return retVal.Body.GetViewAsXmlResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.ClientPRDSupplier.SetViewFilterResponse Demo.ClientPRDSupplier.SupplierServiceSoap.SetViewFilter(Demo.ClientPRDSupplier.SetViewFilterRequest request) {
            return base.Channel.SetViewFilter(request);
        }
        
        public string SetViewFilter(string sessionHandle, Demo.ClientPRDSupplier.SupplierFilterField[] filterFields, Demo.ClientPRDSupplier.ArrayOfString filterValues) {
            Demo.ClientPRDSupplier.SetViewFilterRequest inValue = new Demo.ClientPRDSupplier.SetViewFilterRequest();
            inValue.Body = new Demo.ClientPRDSupplier.SetViewFilterRequestBody();
            inValue.Body.sessionHandle = sessionHandle;
            inValue.Body.filterFields = filterFields;
            inValue.Body.filterValues = filterValues;
            Demo.ClientPRDSupplier.SetViewFilterResponse retVal = ((Demo.ClientPRDSupplier.SupplierServiceSoap)(this)).SetViewFilter(inValue);
            return retVal.Body.SetViewFilterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.ClientPRDSupplier.SetViewSortOrderResponse Demo.ClientPRDSupplier.SupplierServiceSoap.SetViewSortOrder(Demo.ClientPRDSupplier.SetViewSortOrderRequest request) {
            return base.Channel.SetViewSortOrder(request);
        }
        
        public string SetViewSortOrder(string sessionHandle, string sortExpression) {
            Demo.ClientPRDSupplier.SetViewSortOrderRequest inValue = new Demo.ClientPRDSupplier.SetViewSortOrderRequest();
            inValue.Body = new Demo.ClientPRDSupplier.SetViewSortOrderRequestBody();
            inValue.Body.sessionHandle = sessionHandle;
            inValue.Body.sortExpression = sortExpression;
            Demo.ClientPRDSupplier.SetViewSortOrderResponse retVal = ((Demo.ClientPRDSupplier.SupplierServiceSoap)(this)).SetViewSortOrder(inValue);
            return retVal.Body.SetViewSortOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.ClientPRDSupplier.GetViewCountResponse Demo.ClientPRDSupplier.SupplierServiceSoap.GetViewCount(Demo.ClientPRDSupplier.GetViewCountRequest request) {
            return base.Channel.GetViewCount(request);
        }
        
        public string GetViewCount(string sessionHandle, out int recordCount) {
            Demo.ClientPRDSupplier.GetViewCountRequest inValue = new Demo.ClientPRDSupplier.GetViewCountRequest();
            inValue.Body = new Demo.ClientPRDSupplier.GetViewCountRequestBody();
            inValue.Body.sessionHandle = sessionHandle;
            Demo.ClientPRDSupplier.GetViewCountResponse retVal = ((Demo.ClientPRDSupplier.SupplierServiceSoap)(this)).GetViewCount(inValue);
            recordCount = retVal.Body.recordCount;
            return retVal.Body.GetViewCountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.ClientPRDSupplier.ResetViewFilterResponse Demo.ClientPRDSupplier.SupplierServiceSoap.ResetViewFilter(Demo.ClientPRDSupplier.ResetViewFilterRequest request) {
            return base.Channel.ResetViewFilter(request);
        }
        
        public string ResetViewFilter(string sessionHandle) {
            Demo.ClientPRDSupplier.ResetViewFilterRequest inValue = new Demo.ClientPRDSupplier.ResetViewFilterRequest();
            inValue.Body = new Demo.ClientPRDSupplier.ResetViewFilterRequestBody();
            inValue.Body.sessionHandle = sessionHandle;
            Demo.ClientPRDSupplier.ResetViewFilterResponse retVal = ((Demo.ClientPRDSupplier.SupplierServiceSoap)(this)).ResetViewFilter(inValue);
            return retVal.Body.ResetViewFilterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.ClientPRDSupplier.SetViewAdvancedFilterResponse Demo.ClientPRDSupplier.SupplierServiceSoap.SetViewAdvancedFilter(Demo.ClientPRDSupplier.SetViewAdvancedFilterRequest request) {
            return base.Channel.SetViewAdvancedFilter(request);
        }
        
        public string SetViewAdvancedFilter(string sessionHandle, Demo.ClientPRDSupplier.FilterElement[] filterElements) {
            Demo.ClientPRDSupplier.SetViewAdvancedFilterRequest inValue = new Demo.ClientPRDSupplier.SetViewAdvancedFilterRequest();
            inValue.Body = new Demo.ClientPRDSupplier.SetViewAdvancedFilterRequestBody();
            inValue.Body.sessionHandle = sessionHandle;
            inValue.Body.filterElements = filterElements;
            Demo.ClientPRDSupplier.SetViewAdvancedFilterResponse retVal = ((Demo.ClientPRDSupplier.SupplierServiceSoap)(this)).SetViewAdvancedFilter(inValue);
            return retVal.Body.SetViewAdvancedFilterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.ClientPRDSupplier.SetViewSearchTextResponse Demo.ClientPRDSupplier.SupplierServiceSoap.SetViewSearchText(Demo.ClientPRDSupplier.SetViewSearchTextRequest request) {
            return base.Channel.SetViewSearchText(request);
        }
        
        public string SetViewSearchText(string sessionHandle, string searchText) {
            Demo.ClientPRDSupplier.SetViewSearchTextRequest inValue = new Demo.ClientPRDSupplier.SetViewSearchTextRequest();
            inValue.Body = new Demo.ClientPRDSupplier.SetViewSearchTextRequestBody();
            inValue.Body.sessionHandle = sessionHandle;
            inValue.Body.searchText = searchText;
            Demo.ClientPRDSupplier.SetViewSearchTextResponse retVal = ((Demo.ClientPRDSupplier.SupplierServiceSoap)(this)).SetViewSearchText(inValue);
            return retVal.Body.SetViewSearchTextResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.ClientPRDSupplier.SetViewFacetResponse Demo.ClientPRDSupplier.SupplierServiceSoap.SetViewFacet(Demo.ClientPRDSupplier.SetViewFacetRequest request) {
            return base.Channel.SetViewFacet(request);
        }
        
        public string SetViewFacet(string sessionHandle, string selectedFacetItem, out Demo.ClientPRDSupplier.Facet[] facets, out int recordCount) {
            Demo.ClientPRDSupplier.SetViewFacetRequest inValue = new Demo.ClientPRDSupplier.SetViewFacetRequest();
            inValue.Body = new Demo.ClientPRDSupplier.SetViewFacetRequestBody();
            inValue.Body.sessionHandle = sessionHandle;
            inValue.Body.selectedFacetItem = selectedFacetItem;
            Demo.ClientPRDSupplier.SetViewFacetResponse retVal = ((Demo.ClientPRDSupplier.SupplierServiceSoap)(this)).SetViewFacet(inValue);
            facets = retVal.Body.facets;
            recordCount = retVal.Body.recordCount;
            return retVal.Body.SetViewFacetResult;
        }
    }
}
