//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.ClientMessageService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Security", Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
        "")]
    [System.SerializableAttribute()]
    public partial class Security : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Demo.ClientMessageService.Timestamp TimestampField;
        
        private Demo.ClientMessageService.UsernameToken UsernameTokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Demo.ClientMessageService.Timestamp Timestamp {
            get {
                return this.TimestampField;
            }
            set {
                if ((object.ReferenceEquals(this.TimestampField, value) != true)) {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Demo.ClientMessageService.UsernameToken UsernameToken {
            get {
                return this.UsernameTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameTokenField, value) != true)) {
                    this.UsernameTokenField = value;
                    this.RaisePropertyChanged("UsernameToken");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Timestamp", Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xs" +
        "d")]
    [System.SerializableAttribute()]
    public partial class Timestamp : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ExpiresField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Created {
            get {
                return this.CreatedField;
            }
            set {
                if ((this.CreatedField.Equals(value) != true)) {
                    this.CreatedField = value;
                    this.RaisePropertyChanged("Created");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Expires {
            get {
                return this.ExpiresField;
            }
            set {
                if ((this.ExpiresField.Equals(value) != true)) {
                    this.ExpiresField = value;
                    this.RaisePropertyChanged("Expires");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsernameToken", Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
        "")]
    [System.SerializableAttribute()]
    public partial class UsernameToken : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string UsernameField;
        
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomInfoType", Namespace="")]
    [System.SerializableAttribute()]
    public partial class CustomInfoType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool IsTestMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsContentCompressedField;
        
        private string ApplicationIdField;
        
        private string VersionIdField;
        
        private string RelationIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool IsTestMessage {
            get {
                return this.IsTestMessageField;
            }
            set {
                if ((this.IsTestMessageField.Equals(value) != true)) {
                    this.IsTestMessageField = value;
                    this.RaisePropertyChanged("IsTestMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LanguageCode {
            get {
                return this.LanguageCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageCodeField, value) != true)) {
                    this.LanguageCodeField = value;
                    this.RaisePropertyChanged("LanguageCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Nullable<bool> IsContentCompressed {
            get {
                return this.IsContentCompressedField;
            }
            set {
                if ((this.IsContentCompressedField.Equals(value) != true)) {
                    this.IsContentCompressedField = value;
                    this.RaisePropertyChanged("IsContentCompressed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string ApplicationId {
            get {
                return this.ApplicationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationIdField, value) != true)) {
                    this.ApplicationIdField = value;
                    this.RaisePropertyChanged("ApplicationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public string VersionId {
            get {
                return this.VersionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionIdField, value) != true)) {
                    this.VersionIdField = value;
                    this.RaisePropertyChanged("VersionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public string RelationId {
            get {
                return this.RelationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RelationIdField, value) != true)) {
                    this.RelationIdField = value;
                    this.RaisePropertyChanged("RelationId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageRequestType", Namespace="")]
    [System.SerializableAttribute()]
    public partial class MessageRequestType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string MsgIdField;
        
        private System.Nullable<Demo.ClientMessageService.MsgFormatType> MsgFormatField;
        
        private string MsgVersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string MsgId {
            get {
                return this.MsgIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgIdField, value) != true)) {
                    this.MsgIdField = value;
                    this.RaisePropertyChanged("MsgId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.Nullable<Demo.ClientMessageService.MsgFormatType> MsgFormat {
            get {
                return this.MsgFormatField;
            }
            set {
                if ((this.MsgFormatField.Equals(value) != true)) {
                    this.MsgFormatField = value;
                    this.RaisePropertyChanged("MsgFormat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string MsgVersion {
            get {
                return this.MsgVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgVersionField, value) != true)) {
                    this.MsgVersionField = value;
                    this.RaisePropertyChanged("MsgVersion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MsgFormatType", Namespace="http://schemas.datacontract.org/2004/07/MessageService.Models.Enum")]
    public enum MsgFormatType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INSBOU = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        D96A = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KETENSTANDAARD = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CUSTOM = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SALES = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ETIM = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UNKNOWN = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NONE = 7,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageRequestResponseType", Namespace="")]
    [System.SerializableAttribute()]
    public partial class MessageRequestResponseType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Demo.ClientMessageService.MessageType MessageRequestResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Demo.ClientMessageService.MessageType MessageRequestResult {
            get {
                return this.MessageRequestResultField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageRequestResultField, value) != true)) {
                    this.MessageRequestResultField = value;
                    this.RaisePropertyChanged("MessageRequestResult");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageType", Namespace="")]
    [System.SerializableAttribute()]
    public partial class MessageType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Demo.ClientMessageService.MessageList MsgPropertiesField;
        
        private string MsgContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Demo.ClientMessageService.AttachmentType[] AttachmentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Demo.ClientMessageService.MessageList MsgProperties {
            get {
                return this.MsgPropertiesField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgPropertiesField, value) != true)) {
                    this.MsgPropertiesField = value;
                    this.RaisePropertyChanged("MsgProperties");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string MsgContent {
            get {
                return this.MsgContentField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgContentField, value) != true)) {
                    this.MsgContentField = value;
                    this.RaisePropertyChanged("MsgContent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Demo.ClientMessageService.AttachmentType[] Attachment {
            get {
                return this.AttachmentField;
            }
            set {
                if ((object.ReferenceEquals(this.AttachmentField, value) != true)) {
                    this.AttachmentField = value;
                    this.RaisePropertyChanged("Attachment");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageList", Namespace="")]
    [System.SerializableAttribute()]
    public partial class MessageList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string MsgIdField;
        
        private System.Nullable<System.DateTime> MsgDateTimeField;
        
        private System.Nullable<Demo.ClientMessageService.MsgFormatType> MsgFormatField;
        
        private string MsgVersionField;
        
        private string MsgTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string MsgId {
            get {
                return this.MsgIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgIdField, value) != true)) {
                    this.MsgIdField = value;
                    this.RaisePropertyChanged("MsgId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.Nullable<System.DateTime> MsgDateTime {
            get {
                return this.MsgDateTimeField;
            }
            set {
                if ((this.MsgDateTimeField.Equals(value) != true)) {
                    this.MsgDateTimeField = value;
                    this.RaisePropertyChanged("MsgDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<Demo.ClientMessageService.MsgFormatType> MsgFormat {
            get {
                return this.MsgFormatField;
            }
            set {
                if ((this.MsgFormatField.Equals(value) != true)) {
                    this.MsgFormatField = value;
                    this.RaisePropertyChanged("MsgFormat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string MsgVersion {
            get {
                return this.MsgVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgVersionField, value) != true)) {
                    this.MsgVersionField = value;
                    this.RaisePropertyChanged("MsgVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public string MsgType {
            get {
                return this.MsgTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgTypeField, value) != true)) {
                    this.MsgTypeField = value;
                    this.RaisePropertyChanged("MsgType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AttachmentType", Namespace="")]
    [System.SerializableAttribute()]
    public partial class AttachmentType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string URLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentTypeField;
        
        private string FileTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        private byte[] AttachedDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string DocumentType {
            get {
                return this.DocumentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentTypeField, value) != true)) {
                    this.DocumentTypeField = value;
                    this.RaisePropertyChanged("DocumentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string FileType {
            get {
                return this.FileTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.FileTypeField, value) != true)) {
                    this.FileTypeField = value;
                    this.RaisePropertyChanged("FileType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public byte[] AttachedData {
            get {
                return this.AttachedDataField;
            }
            set {
                if ((object.ReferenceEquals(this.AttachedDataField, value) != true)) {
                    this.AttachedDataField = value;
                    this.RaisePropertyChanged("AttachedData");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultError", Namespace="http://schemas.datacontract.org/2004/07/MessageService.FaultHandling")]
    [System.SerializableAttribute()]
    public partial class FaultError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaultCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Demo.ClientMessageService.FaultDetails FaultDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaultStringField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaultCode {
            get {
                return this.FaultCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.FaultCodeField, value) != true)) {
                    this.FaultCodeField = value;
                    this.RaisePropertyChanged("FaultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Demo.ClientMessageService.FaultDetails FaultDetails {
            get {
                return this.FaultDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.FaultDetailsField, value) != true)) {
                    this.FaultDetailsField = value;
                    this.RaisePropertyChanged("FaultDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaultString {
            get {
                return this.FaultStringField;
            }
            set {
                if ((object.ReferenceEquals(this.FaultStringField, value) != true)) {
                    this.FaultStringField = value;
                    this.RaisePropertyChanged("FaultString");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultDetails", Namespace="http://schemas.datacontract.org/2004/07/MessageService.FaultHandling")]
    [System.SerializableAttribute()]
    public partial class FaultDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageResponseType", Namespace="")]
    [System.SerializableAttribute()]
    public partial class MessageResponseType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Demo.ClientMessageService.MessageType MessageField;
        
        private bool MessageResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Demo.ClientMessageService.MessageType Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool MessageResult {
            get {
                return this.MessageResultField;
            }
            set {
                if ((this.MessageResultField.Equals(value) != true)) {
                    this.MessageResultField = value;
                    this.RaisePropertyChanged("MessageResult");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AvailableMessagesRequestType", Namespace="")]
    [System.SerializableAttribute()]
    public partial class AvailableMessagesRequestType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string MsgTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string MsgType {
            get {
                return this.MsgTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgTypeField, value) != true)) {
                    this.MsgTypeField = value;
                    this.RaisePropertyChanged("MsgType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://www.ketenstandaard.nl/WS/MessageService/3.0", ConfigurationName="ClientMessageService.MessageServiceSoap")]
    public interface MessageServiceSoap {
        
        // CODEGEN: Generating message contract since the operation GetMessage is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="messageservice/GetMessage", ReplyAction="https://www.ketenstandaard.nl/WS/MessageService/3.0/MessageServiceSoap/GetMessage" +
            "Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(Demo.ClientMessageService.FaultError), Action="https://www.ketenstandaard.nl/WS/MessageService/3.0/MessageServiceSoap/GetMessage" +
            "FaultErrorFault", Name="FaultError", Namespace="http://schemas.datacontract.org/2004/07/MessageService.FaultHandling")]
        Demo.ClientMessageService.GetMessageResponse GetMessage(Demo.ClientMessageService.GetMessageRequest request);
        
        // CODEGEN: Generating message contract since the operation DeleteMessage is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="messageservice/DeleteMessage", ReplyAction="https://www.ketenstandaard.nl/WS/MessageService/3.0/MessageServiceSoap/DeleteMess" +
            "ageResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Demo.ClientMessageService.FaultError), Action="https://www.ketenstandaard.nl/WS/MessageService/3.0/MessageServiceSoap/DeleteMess" +
            "ageFaultErrorFault", Name="FaultError", Namespace="http://schemas.datacontract.org/2004/07/MessageService.FaultHandling")]
        Demo.ClientMessageService.DeleteMessageResponse DeleteMessage(Demo.ClientMessageService.DeleteMessageRequest request);
        
        // CODEGEN: Generating message contract since the operation GetAvailableMessages is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="messageservice/GetAvailableMessages", ReplyAction="https://www.ketenstandaard.nl/WS/MessageService/3.0/MessageServiceSoap/GetAvailab" +
            "leMessagesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Demo.ClientMessageService.FaultError), Action="https://www.ketenstandaard.nl/WS/MessageService/3.0/MessageServiceSoap/GetAvailab" +
            "leMessagesFaultErrorFault", Name="FaultError", Namespace="http://schemas.datacontract.org/2004/07/MessageService.FaultHandling")]
        Demo.ClientMessageService.GetAvailableMessagesResponse GetAvailableMessages(Demo.ClientMessageService.GetAvailableMessagesRequest request);
        
        // CODEGEN: Generating message contract since the operation PostMessage is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="messageservice/PostMessage", ReplyAction="https://www.ketenstandaard.nl/WS/MessageService/3.0/MessageServiceSoap/PostMessag" +
            "eResponse")]
        Demo.ClientMessageService.DeleteMessageResponse PostMessage(Demo.ClientMessageService.PostMessageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessageRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
            "")]
        public Demo.ClientMessageService.Security Security;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://www.ketenstandaard.nl/WS/MessageService/3.0")]
        public Demo.ClientMessageService.CustomInfoType CustomInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.ketenstandaard.nl/WS/MessageService/3.0", Order=0)]
        public Demo.ClientMessageService.MessageRequestType MessageRequest;
        
        public GetMessageRequest() {
        }
        
        public GetMessageRequest(Demo.ClientMessageService.Security Security, Demo.ClientMessageService.CustomInfoType CustomInfo, Demo.ClientMessageService.MessageRequestType MessageRequest) {
            this.Security = Security;
            this.CustomInfo = CustomInfo;
            this.MessageRequest = MessageRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.ketenstandaard.nl/WS/MessageService/3.0", Order=0)]
        public Demo.ClientMessageService.MessageRequestResponseType MessageRequestResponse;
        
        public GetMessageResponse() {
        }
        
        public GetMessageResponse(Demo.ClientMessageService.MessageRequestResponseType MessageRequestResponse) {
            this.MessageRequestResponse = MessageRequestResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteMessageRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
            "")]
        public Demo.ClientMessageService.Security Security;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://www.ketenstandaard.nl/WS/MessageService/3.0")]
        public Demo.ClientMessageService.CustomInfoType CustomInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.ketenstandaard.nl/WS/MessageService/3.0", Order=0)]
        public Demo.ClientMessageService.MessageRequestType MessageRequest;
        
        public DeleteMessageRequest() {
        }
        
        public DeleteMessageRequest(Demo.ClientMessageService.Security Security, Demo.ClientMessageService.CustomInfoType CustomInfo, Demo.ClientMessageService.MessageRequestType MessageRequest) {
            this.Security = Security;
            this.CustomInfo = CustomInfo;
            this.MessageRequest = MessageRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.ketenstandaard.nl/WS/MessageService/3.0", Order=0)]
        public Demo.ClientMessageService.MessageResponseType MessageResponse;
        
        public DeleteMessageResponse() {
        }
        
        public DeleteMessageResponse(Demo.ClientMessageService.MessageResponseType MessageResponse) {
            this.MessageResponse = MessageResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAvailableMessagesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
            "")]
        public Demo.ClientMessageService.Security Security;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://www.ketenstandaard.nl/WS/MessageService/3.0")]
        public Demo.ClientMessageService.CustomInfoType CustomInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.ketenstandaard.nl/WS/MessageService/3.0", Order=0)]
        public Demo.ClientMessageService.AvailableMessagesRequestType AvailableMessagesRequest;
        
        public GetAvailableMessagesRequest() {
        }
        
        public GetAvailableMessagesRequest(Demo.ClientMessageService.Security Security, Demo.ClientMessageService.CustomInfoType CustomInfo, Demo.ClientMessageService.AvailableMessagesRequestType AvailableMessagesRequest) {
            this.Security = Security;
            this.CustomInfo = CustomInfo;
            this.AvailableMessagesRequest = AvailableMessagesRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAvailableMessagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.ketenstandaard.nl/WS/MessageService/3.0", Order=0)]
        public Demo.ClientMessageService.MessageList[] AvailableMessagesResponse;
        
        public GetAvailableMessagesResponse() {
        }
        
        public GetAvailableMessagesResponse(Demo.ClientMessageService.MessageList[] AvailableMessagesResponse) {
            this.AvailableMessagesResponse = AvailableMessagesResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostMessageRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
            "")]
        public Demo.ClientMessageService.Security Security;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://www.ketenstandaard.nl/WS/MessageService/3.0")]
        public Demo.ClientMessageService.CustomInfoType CustomInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.ketenstandaard.nl/WS/MessageService/3.0", Order=0)]
        public Demo.ClientMessageService.MessageType Message;
        
        public PostMessageRequest() {
        }
        
        public PostMessageRequest(Demo.ClientMessageService.Security Security, Demo.ClientMessageService.CustomInfoType CustomInfo, Demo.ClientMessageService.MessageType Message) {
            this.Security = Security;
            this.CustomInfo = CustomInfo;
            this.Message = Message;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MessageServiceSoapChannel : Demo.ClientMessageService.MessageServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MessageServiceSoapClient : System.ServiceModel.ClientBase<Demo.ClientMessageService.MessageServiceSoap>, Demo.ClientMessageService.MessageServiceSoap {
        
        public MessageServiceSoapClient() {
        }
        
        public MessageServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MessageServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.ClientMessageService.GetMessageResponse Demo.ClientMessageService.MessageServiceSoap.GetMessage(Demo.ClientMessageService.GetMessageRequest request) {
            return base.Channel.GetMessage(request);
        }
        
        public Demo.ClientMessageService.MessageRequestResponseType GetMessage(Demo.ClientMessageService.Security Security, Demo.ClientMessageService.CustomInfoType CustomInfo, Demo.ClientMessageService.MessageRequestType MessageRequest) {
            Demo.ClientMessageService.GetMessageRequest inValue = new Demo.ClientMessageService.GetMessageRequest();
            inValue.Security = Security;
            inValue.CustomInfo = CustomInfo;
            inValue.MessageRequest = MessageRequest;
            Demo.ClientMessageService.GetMessageResponse retVal = ((Demo.ClientMessageService.MessageServiceSoap)(this)).GetMessage(inValue);
            return retVal.MessageRequestResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.ClientMessageService.DeleteMessageResponse Demo.ClientMessageService.MessageServiceSoap.DeleteMessage(Demo.ClientMessageService.DeleteMessageRequest request) {
            return base.Channel.DeleteMessage(request);
        }
        
        public Demo.ClientMessageService.MessageResponseType DeleteMessage(Demo.ClientMessageService.Security Security, Demo.ClientMessageService.CustomInfoType CustomInfo, Demo.ClientMessageService.MessageRequestType MessageRequest) {
            Demo.ClientMessageService.DeleteMessageRequest inValue = new Demo.ClientMessageService.DeleteMessageRequest();
            inValue.Security = Security;
            inValue.CustomInfo = CustomInfo;
            inValue.MessageRequest = MessageRequest;
            Demo.ClientMessageService.DeleteMessageResponse retVal = ((Demo.ClientMessageService.MessageServiceSoap)(this)).DeleteMessage(inValue);
            return retVal.MessageResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.ClientMessageService.GetAvailableMessagesResponse Demo.ClientMessageService.MessageServiceSoap.GetAvailableMessages(Demo.ClientMessageService.GetAvailableMessagesRequest request) {
            return base.Channel.GetAvailableMessages(request);
        }
        
        public Demo.ClientMessageService.MessageList[] GetAvailableMessages(Demo.ClientMessageService.Security Security, Demo.ClientMessageService.CustomInfoType CustomInfo, Demo.ClientMessageService.AvailableMessagesRequestType AvailableMessagesRequest) {
            Demo.ClientMessageService.GetAvailableMessagesRequest inValue = new Demo.ClientMessageService.GetAvailableMessagesRequest();
            inValue.Security = Security;
            inValue.CustomInfo = CustomInfo;
            inValue.AvailableMessagesRequest = AvailableMessagesRequest;
            Demo.ClientMessageService.GetAvailableMessagesResponse retVal = ((Demo.ClientMessageService.MessageServiceSoap)(this)).GetAvailableMessages(inValue);
            return retVal.AvailableMessagesResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.ClientMessageService.DeleteMessageResponse Demo.ClientMessageService.MessageServiceSoap.PostMessage(Demo.ClientMessageService.PostMessageRequest request) {
            return base.Channel.PostMessage(request);
        }
        
        public Demo.ClientMessageService.MessageResponseType PostMessage(Demo.ClientMessageService.Security Security, Demo.ClientMessageService.CustomInfoType CustomInfo, Demo.ClientMessageService.MessageType Message) {
            Demo.ClientMessageService.PostMessageRequest inValue = new Demo.ClientMessageService.PostMessageRequest();
            inValue.Security = Security;
            inValue.CustomInfo = CustomInfo;
            inValue.Message = Message;
            Demo.ClientMessageService.DeleteMessageResponse retVal = ((Demo.ClientMessageService.MessageServiceSoap)(this)).PostMessage(inValue);
            return retVal.MessageResponse;
        }
    }
}
