//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.MessageService240TestCompano {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationInfo", Namespace="http://etim.nl/xmlschemas/messageservice/2.40")]
    [System.SerializableAttribute()]
    public partial class AuthenticationInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VersionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RelationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SessionIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ApplicationId {
            get {
                return this.ApplicationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationIdField, value) != true)) {
                    this.ApplicationIdField = value;
                    this.RaisePropertyChanged("ApplicationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string VersionId {
            get {
                return this.VersionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionIdField, value) != true)) {
                    this.VersionIdField = value;
                    this.RaisePropertyChanged("VersionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string RelationId {
            get {
                return this.RelationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RelationIdField, value) != true)) {
                    this.RelationIdField = value;
                    this.RaisePropertyChanged("RelationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string SessionId {
            get {
                return this.SessionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionIdField, value) != true)) {
                    this.SessionIdField = value;
                    this.RaisePropertyChanged("SessionId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomInfo", Namespace="http://etim.nl/xmlschemas/messageservice/2.40")]
    [System.SerializableAttribute()]
    public partial class CustomInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool IsTestMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageCodeField;
        
        private System.Nullable<bool> IsContentCompressedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool IsTestMessage {
            get {
                return this.IsTestMessageField;
            }
            set {
                if ((this.IsTestMessageField.Equals(value) != true)) {
                    this.IsTestMessageField = value;
                    this.RaisePropertyChanged("IsTestMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LanguageCode {
            get {
                return this.LanguageCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageCodeField, value) != true)) {
                    this.LanguageCodeField = value;
                    this.RaisePropertyChanged("LanguageCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<bool> IsContentCompressed {
            get {
                return this.IsContentCompressedField;
            }
            set {
                if ((this.IsContentCompressedField.Equals(value) != true)) {
                    this.IsContentCompressedField = value;
                    this.RaisePropertyChanged("IsContentCompressed");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MsgTypeOption", Namespace="http://etim.nl/xmlschemas/messageservice/2.40")]
    public enum MsgTypeOption : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PRICAT = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PRODAT = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TRMMSG = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        REQOTE = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QUOTES = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ORDERS = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ORDCHG = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ORDRSP = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ORSSTA = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ORDREP = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DESADV = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVOIC = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        COLINV = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVRPT = 13,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AvailableMessage", Namespace="http://etim.nl/xmlschemas/messageservice/2.40")]
    [System.SerializableAttribute()]
    public partial class AvailableMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsgIdField;
        
        private System.DateTime MsgDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Demo.MessageService240TestCompano.AvailableFormat[] AvailableFormatField;
        
        private Demo.MessageService240TestCompano.MsgTypeOption MsgTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MsgId {
            get {
                return this.MsgIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgIdField, value) != true)) {
                    this.MsgIdField = value;
                    this.RaisePropertyChanged("MsgId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime MsgDateTime {
            get {
                return this.MsgDateTimeField;
            }
            set {
                if ((this.MsgDateTimeField.Equals(value) != true)) {
                    this.MsgDateTimeField = value;
                    this.RaisePropertyChanged("MsgDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Demo.MessageService240TestCompano.AvailableFormat[] AvailableFormat {
            get {
                return this.AvailableFormatField;
            }
            set {
                if ((object.ReferenceEquals(this.AvailableFormatField, value) != true)) {
                    this.AvailableFormatField = value;
                    this.RaisePropertyChanged("AvailableFormat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public Demo.MessageService240TestCompano.MsgTypeOption MsgType {
            get {
                return this.MsgTypeField;
            }
            set {
                if ((this.MsgTypeField.Equals(value) != true)) {
                    this.MsgTypeField = value;
                    this.RaisePropertyChanged("MsgType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AvailableFormat", Namespace="http://etim.nl/xmlschemas/messageservice/2.40")]
    [System.SerializableAttribute()]
    public partial class AvailableFormat : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Demo.MessageService240TestCompano.MsgFormatOption MsgFormatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsgVersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Demo.MessageService240TestCompano.MsgFormatOption MsgFormat {
            get {
                return this.MsgFormatField;
            }
            set {
                if ((this.MsgFormatField.Equals(value) != true)) {
                    this.MsgFormatField = value;
                    this.RaisePropertyChanged("MsgFormat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MsgVersion {
            get {
                return this.MsgVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgVersionField, value) != true)) {
                    this.MsgVersionField = value;
                    this.RaisePropertyChanged("MsgVersion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MsgFormatOption", Namespace="http://etim.nl/xmlschemas/messageservice/2.40")]
    public enum MsgFormatOption : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INSBOU = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ETIM = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SALES = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        D96A = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CUSTOM = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://etim.nl/xmlschemas/messageservice/2.40")]
    [System.SerializableAttribute()]
    public partial class Message : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsgIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsgTypeField;
        
        private Demo.MessageService240TestCompano.MsgFormatOption MsgFormatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsgVersionField;
        
        private System.Nullable<System.DateTime> MsgDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Demo.MessageService240TestCompano.Attachment[] AttachmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsgContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Demo.MessageService240TestCompano.ArrayOfString TextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MsgId {
            get {
                return this.MsgIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgIdField, value) != true)) {
                    this.MsgIdField = value;
                    this.RaisePropertyChanged("MsgId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MsgType {
            get {
                return this.MsgTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgTypeField, value) != true)) {
                    this.MsgTypeField = value;
                    this.RaisePropertyChanged("MsgType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public Demo.MessageService240TestCompano.MsgFormatOption MsgFormat {
            get {
                return this.MsgFormatField;
            }
            set {
                if ((this.MsgFormatField.Equals(value) != true)) {
                    this.MsgFormatField = value;
                    this.RaisePropertyChanged("MsgFormat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string MsgVersion {
            get {
                return this.MsgVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgVersionField, value) != true)) {
                    this.MsgVersionField = value;
                    this.RaisePropertyChanged("MsgVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<System.DateTime> MsgDateTime {
            get {
                return this.MsgDateTimeField;
            }
            set {
                if ((this.MsgDateTimeField.Equals(value) != true)) {
                    this.MsgDateTimeField = value;
                    this.RaisePropertyChanged("MsgDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public Demo.MessageService240TestCompano.Attachment[] Attachment {
            get {
                return this.AttachmentField;
            }
            set {
                if ((object.ReferenceEquals(this.AttachmentField, value) != true)) {
                    this.AttachmentField = value;
                    this.RaisePropertyChanged("Attachment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string MsgContent {
            get {
                return this.MsgContentField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgContentField, value) != true)) {
                    this.MsgContentField = value;
                    this.RaisePropertyChanged("MsgContent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public Demo.MessageService240TestCompano.ArrayOfString Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Attachment", Namespace="http://etim.nl/xmlschemas/messageservice/2.40")]
    [System.SerializableAttribute()]
    public partial class Attachment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        private Demo.MessageService240TestCompano.DocumentTypeOption DocumentTypeField;
        
        private Demo.MessageService240TestCompano.FileTypeOption FileTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] AttachedDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public Demo.MessageService240TestCompano.DocumentTypeOption DocumentType {
            get {
                return this.DocumentTypeField;
            }
            set {
                if ((this.DocumentTypeField.Equals(value) != true)) {
                    this.DocumentTypeField = value;
                    this.RaisePropertyChanged("DocumentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public Demo.MessageService240TestCompano.FileTypeOption FileType {
            get {
                return this.FileTypeField;
            }
            set {
                if ((this.FileTypeField.Equals(value) != true)) {
                    this.FileTypeField = value;
                    this.RaisePropertyChanged("FileType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public byte[] AttachedData {
            get {
                return this.AttachedDataField;
            }
            set {
                if ((object.ReferenceEquals(this.AttachedDataField, value) != true)) {
                    this.AttachedDataField = value;
                    this.RaisePropertyChanged("AttachedData");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://etim.nl/xmlschemas/messageservice/2.40", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentTypeOption", Namespace="http://etim.nl/xmlschemas/messageservice/2.40")]
    public enum DocumentTypeOption : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DOC = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FAC = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OTH = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PIC = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileTypeOption", Namespace="http://etim.nl/xmlschemas/messageservice/2.40")]
    public enum FileTypeOption : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DOC = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GIF = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        JPG = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PDF = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PNG = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XLS = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://etim.nl/xmlschemas/messageservice/2.40", ConfigurationName="MessageService240TestCompano.MessageServiceSoap")]
    public interface MessageServiceSoap {
        
        // CODEGEN: Generating message contract since element name authenticationInfo from namespace http://etim.nl/xmlschemas/messageservice/2.40 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://etim.nl/xmlschemas/messageservice/2.40/GetAvailableMessages", ReplyAction="*")]
        Demo.MessageService240TestCompano.GetAvailableMessagesResponse GetAvailableMessages(Demo.MessageService240TestCompano.GetAvailableMessagesRequest request);
        
        // CODEGEN: Generating message contract since element name authenticationInfo from namespace http://etim.nl/xmlschemas/messageservice/2.40 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://etim.nl/xmlschemas/messageservice/2.40/GetMessage", ReplyAction="*")]
        Demo.MessageService240TestCompano.GetMessageResponse GetMessage(Demo.MessageService240TestCompano.GetMessageRequest request);
        
        // CODEGEN: Generating message contract since element name authenticationInfo from namespace http://etim.nl/xmlschemas/messageservice/2.40 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://etim.nl/xmlschemas/messageservice/2.40/DeleteMessage", ReplyAction="*")]
        Demo.MessageService240TestCompano.DeleteMessageResponse DeleteMessage(Demo.MessageService240TestCompano.DeleteMessageRequest request);
        
        // CODEGEN: Generating message contract since element name authenticationInfo from namespace http://etim.nl/xmlschemas/messageservice/2.40 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://etim.nl/xmlschemas/messageservice/2.40/PostMessage", ReplyAction="*")]
        Demo.MessageService240TestCompano.PostMessageResponse PostMessage(Demo.MessageService240TestCompano.PostMessageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAvailableMessagesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAvailableMessages", Namespace="http://etim.nl/xmlschemas/messageservice/2.40", Order=0)]
        public Demo.MessageService240TestCompano.GetAvailableMessagesRequestBody Body;
        
        public GetAvailableMessagesRequest() {
        }
        
        public GetAvailableMessagesRequest(Demo.MessageService240TestCompano.GetAvailableMessagesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://etim.nl/xmlschemas/messageservice/2.40")]
    public partial class GetAvailableMessagesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Demo.MessageService240TestCompano.AuthenticationInfo authenticationInfo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Demo.MessageService240TestCompano.CustomInfo customInfo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public Demo.MessageService240TestCompano.MsgTypeOption msgType;
        
        public GetAvailableMessagesRequestBody() {
        }
        
        public GetAvailableMessagesRequestBody(Demo.MessageService240TestCompano.AuthenticationInfo authenticationInfo, Demo.MessageService240TestCompano.CustomInfo customInfo, Demo.MessageService240TestCompano.MsgTypeOption msgType) {
            this.authenticationInfo = authenticationInfo;
            this.customInfo = customInfo;
            this.msgType = msgType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAvailableMessagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAvailableMessagesResponse", Namespace="http://etim.nl/xmlschemas/messageservice/2.40", Order=0)]
        public Demo.MessageService240TestCompano.GetAvailableMessagesResponseBody Body;
        
        public GetAvailableMessagesResponse() {
        }
        
        public GetAvailableMessagesResponse(Demo.MessageService240TestCompano.GetAvailableMessagesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://etim.nl/xmlschemas/messageservice/2.40")]
    public partial class GetAvailableMessagesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Demo.MessageService240TestCompano.AvailableMessage[] GetAvailableMessagesResult;
        
        public GetAvailableMessagesResponseBody() {
        }
        
        public GetAvailableMessagesResponseBody(Demo.MessageService240TestCompano.AvailableMessage[] GetAvailableMessagesResult) {
            this.GetAvailableMessagesResult = GetAvailableMessagesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessage", Namespace="http://etim.nl/xmlschemas/messageservice/2.40", Order=0)]
        public Demo.MessageService240TestCompano.GetMessageRequestBody Body;
        
        public GetMessageRequest() {
        }
        
        public GetMessageRequest(Demo.MessageService240TestCompano.GetMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://etim.nl/xmlschemas/messageservice/2.40")]
    public partial class GetMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Demo.MessageService240TestCompano.AuthenticationInfo authenticationInfo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Demo.MessageService240TestCompano.CustomInfo customInfo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string msgId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public Demo.MessageService240TestCompano.MsgFormatOption msgFormat;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string msgVersion;
        
        public GetMessageRequestBody() {
        }
        
        public GetMessageRequestBody(Demo.MessageService240TestCompano.AuthenticationInfo authenticationInfo, Demo.MessageService240TestCompano.CustomInfo customInfo, string msgId, Demo.MessageService240TestCompano.MsgFormatOption msgFormat, string msgVersion) {
            this.authenticationInfo = authenticationInfo;
            this.customInfo = customInfo;
            this.msgId = msgId;
            this.msgFormat = msgFormat;
            this.msgVersion = msgVersion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessageResponse", Namespace="http://etim.nl/xmlschemas/messageservice/2.40", Order=0)]
        public Demo.MessageService240TestCompano.GetMessageResponseBody Body;
        
        public GetMessageResponse() {
        }
        
        public GetMessageResponse(Demo.MessageService240TestCompano.GetMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://etim.nl/xmlschemas/messageservice/2.40")]
    public partial class GetMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Demo.MessageService240TestCompano.Message[] GetMessageResult;
        
        public GetMessageResponseBody() {
        }
        
        public GetMessageResponseBody(Demo.MessageService240TestCompano.Message[] GetMessageResult) {
            this.GetMessageResult = GetMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteMessage", Namespace="http://etim.nl/xmlschemas/messageservice/2.40", Order=0)]
        public Demo.MessageService240TestCompano.DeleteMessageRequestBody Body;
        
        public DeleteMessageRequest() {
        }
        
        public DeleteMessageRequest(Demo.MessageService240TestCompano.DeleteMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://etim.nl/xmlschemas/messageservice/2.40")]
    public partial class DeleteMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Demo.MessageService240TestCompano.AuthenticationInfo authenticationInfo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Demo.MessageService240TestCompano.CustomInfo customInfo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string msgId;
        
        public DeleteMessageRequestBody() {
        }
        
        public DeleteMessageRequestBody(Demo.MessageService240TestCompano.AuthenticationInfo authenticationInfo, Demo.MessageService240TestCompano.CustomInfo customInfo, string msgId) {
            this.authenticationInfo = authenticationInfo;
            this.customInfo = customInfo;
            this.msgId = msgId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteMessageResponse", Namespace="http://etim.nl/xmlschemas/messageservice/2.40", Order=0)]
        public Demo.MessageService240TestCompano.DeleteMessageResponseBody Body;
        
        public DeleteMessageResponse() {
        }
        
        public DeleteMessageResponse(Demo.MessageService240TestCompano.DeleteMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://etim.nl/xmlschemas/messageservice/2.40")]
    public partial class DeleteMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool DeleteMessageResult;
        
        public DeleteMessageResponseBody() {
        }
        
        public DeleteMessageResponseBody(bool DeleteMessageResult) {
            this.DeleteMessageResult = DeleteMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostMessage", Namespace="http://etim.nl/xmlschemas/messageservice/2.40", Order=0)]
        public Demo.MessageService240TestCompano.PostMessageRequestBody Body;
        
        public PostMessageRequest() {
        }
        
        public PostMessageRequest(Demo.MessageService240TestCompano.PostMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://etim.nl/xmlschemas/messageservice/2.40")]
    public partial class PostMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Demo.MessageService240TestCompano.AuthenticationInfo authenticationInfo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Demo.MessageService240TestCompano.CustomInfo customInfo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Demo.MessageService240TestCompano.Message messageServiceMessage;
        
        public PostMessageRequestBody() {
        }
        
        public PostMessageRequestBody(Demo.MessageService240TestCompano.AuthenticationInfo authenticationInfo, Demo.MessageService240TestCompano.CustomInfo customInfo, Demo.MessageService240TestCompano.Message messageServiceMessage) {
            this.authenticationInfo = authenticationInfo;
            this.customInfo = customInfo;
            this.messageServiceMessage = messageServiceMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostMessageResponse", Namespace="http://etim.nl/xmlschemas/messageservice/2.40", Order=0)]
        public Demo.MessageService240TestCompano.PostMessageResponseBody Body;
        
        public PostMessageResponse() {
        }
        
        public PostMessageResponse(Demo.MessageService240TestCompano.PostMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://etim.nl/xmlschemas/messageservice/2.40")]
    public partial class PostMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool PostMessageResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Demo.MessageService240TestCompano.Message messageServiceMessage;
        
        public PostMessageResponseBody() {
        }
        
        public PostMessageResponseBody(bool PostMessageResult, Demo.MessageService240TestCompano.Message messageServiceMessage) {
            this.PostMessageResult = PostMessageResult;
            this.messageServiceMessage = messageServiceMessage;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MessageServiceSoapChannel : Demo.MessageService240TestCompano.MessageServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MessageServiceSoapClient : System.ServiceModel.ClientBase<Demo.MessageService240TestCompano.MessageServiceSoap>, Demo.MessageService240TestCompano.MessageServiceSoap {
        
        public MessageServiceSoapClient() {
        }
        
        public MessageServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MessageServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.MessageService240TestCompano.GetAvailableMessagesResponse Demo.MessageService240TestCompano.MessageServiceSoap.GetAvailableMessages(Demo.MessageService240TestCompano.GetAvailableMessagesRequest request) {
            return base.Channel.GetAvailableMessages(request);
        }
        
        public Demo.MessageService240TestCompano.AvailableMessage[] GetAvailableMessages(Demo.MessageService240TestCompano.AuthenticationInfo authenticationInfo, Demo.MessageService240TestCompano.CustomInfo customInfo, Demo.MessageService240TestCompano.MsgTypeOption msgType) {
            Demo.MessageService240TestCompano.GetAvailableMessagesRequest inValue = new Demo.MessageService240TestCompano.GetAvailableMessagesRequest();
            inValue.Body = new Demo.MessageService240TestCompano.GetAvailableMessagesRequestBody();
            inValue.Body.authenticationInfo = authenticationInfo;
            inValue.Body.customInfo = customInfo;
            inValue.Body.msgType = msgType;
            Demo.MessageService240TestCompano.GetAvailableMessagesResponse retVal = ((Demo.MessageService240TestCompano.MessageServiceSoap)(this)).GetAvailableMessages(inValue);
            return retVal.Body.GetAvailableMessagesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.MessageService240TestCompano.GetMessageResponse Demo.MessageService240TestCompano.MessageServiceSoap.GetMessage(Demo.MessageService240TestCompano.GetMessageRequest request) {
            return base.Channel.GetMessage(request);
        }
        
        public Demo.MessageService240TestCompano.Message[] GetMessage(Demo.MessageService240TestCompano.AuthenticationInfo authenticationInfo, Demo.MessageService240TestCompano.CustomInfo customInfo, string msgId, Demo.MessageService240TestCompano.MsgFormatOption msgFormat, string msgVersion) {
            Demo.MessageService240TestCompano.GetMessageRequest inValue = new Demo.MessageService240TestCompano.GetMessageRequest();
            inValue.Body = new Demo.MessageService240TestCompano.GetMessageRequestBody();
            inValue.Body.authenticationInfo = authenticationInfo;
            inValue.Body.customInfo = customInfo;
            inValue.Body.msgId = msgId;
            inValue.Body.msgFormat = msgFormat;
            inValue.Body.msgVersion = msgVersion;
            Demo.MessageService240TestCompano.GetMessageResponse retVal = ((Demo.MessageService240TestCompano.MessageServiceSoap)(this)).GetMessage(inValue);
            return retVal.Body.GetMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.MessageService240TestCompano.DeleteMessageResponse Demo.MessageService240TestCompano.MessageServiceSoap.DeleteMessage(Demo.MessageService240TestCompano.DeleteMessageRequest request) {
            return base.Channel.DeleteMessage(request);
        }
        
        public bool DeleteMessage(Demo.MessageService240TestCompano.AuthenticationInfo authenticationInfo, Demo.MessageService240TestCompano.CustomInfo customInfo, string msgId) {
            Demo.MessageService240TestCompano.DeleteMessageRequest inValue = new Demo.MessageService240TestCompano.DeleteMessageRequest();
            inValue.Body = new Demo.MessageService240TestCompano.DeleteMessageRequestBody();
            inValue.Body.authenticationInfo = authenticationInfo;
            inValue.Body.customInfo = customInfo;
            inValue.Body.msgId = msgId;
            Demo.MessageService240TestCompano.DeleteMessageResponse retVal = ((Demo.MessageService240TestCompano.MessageServiceSoap)(this)).DeleteMessage(inValue);
            return retVal.Body.DeleteMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.MessageService240TestCompano.PostMessageResponse Demo.MessageService240TestCompano.MessageServiceSoap.PostMessage(Demo.MessageService240TestCompano.PostMessageRequest request) {
            return base.Channel.PostMessage(request);
        }
        
        public bool PostMessage(Demo.MessageService240TestCompano.AuthenticationInfo authenticationInfo, Demo.MessageService240TestCompano.CustomInfo customInfo, ref Demo.MessageService240TestCompano.Message messageServiceMessage) {
            Demo.MessageService240TestCompano.PostMessageRequest inValue = new Demo.MessageService240TestCompano.PostMessageRequest();
            inValue.Body = new Demo.MessageService240TestCompano.PostMessageRequestBody();
            inValue.Body.authenticationInfo = authenticationInfo;
            inValue.Body.customInfo = customInfo;
            inValue.Body.messageServiceMessage = messageServiceMessage;
            Demo.MessageService240TestCompano.PostMessageResponse retVal = ((Demo.MessageService240TestCompano.MessageServiceSoap)(this)).PostMessage(inValue);
            messageServiceMessage = retVal.Body.messageServiceMessage;
            return retVal.Body.PostMessageResult;
        }
    }
}
