//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.ClientICSSynonym {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SynonymViewOption", Namespace="http://Compano.com/Modules/ICS")]
    public enum SynonymViewOption : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Synonym = 0,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FilterElement", Namespace="http://Compano.com/Modules/ICS")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientICSSynonym.SynonymViewOption))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientICSSynonym.FilterElement[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientICSSynonym.ConditionTypeOption))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientICSSynonym.SynonymXmlField[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientICSSynonym.SynonymXmlField))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientICSSynonym.SynonymFilterField[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientICSSynonym.SynonymFilterField))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientICSSynonym.ArrayOfString))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientICSSynonym.Facet))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientICSSynonym.FacetItem[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientICSSynonym.FacetItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientICSSynonym.Facet[]))]
    public partial class FilterElement : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Demo.ClientICSSynonym.ConditionTypeOption ConditionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FieldNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object Value1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object Value2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Demo.ClientICSSynonym.ConditionTypeOption ConditionType {
            get {
                return this.ConditionTypeField;
            }
            set {
                if ((this.ConditionTypeField.Equals(value) != true)) {
                    this.ConditionTypeField = value;
                    this.RaisePropertyChanged("ConditionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FieldName {
            get {
                return this.FieldNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldNameField, value) != true)) {
                    this.FieldNameField = value;
                    this.RaisePropertyChanged("FieldName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public object Value1 {
            get {
                return this.Value1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Value1Field, value) != true)) {
                    this.Value1Field = value;
                    this.RaisePropertyChanged("Value1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public object Value2 {
            get {
                return this.Value2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Value2Field, value) != true)) {
                    this.Value2Field = value;
                    this.RaisePropertyChanged("Value2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConditionTypeOption", Namespace="http://Compano.com/Modules/ICS")]
    public enum ConditionTypeOption : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Equals = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EqualsField = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GreaterThan = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GreaterThanField = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GreaterThanOrEquals = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GreaterThanOrEqualsField = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LesserThan = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LesserThanField = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LesserThanOrEquals = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LesserThanOrEqualsField = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Between = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Outside = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Contains = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotContains = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EqualsNoCase = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ItemInSet = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        StartsWith = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EndsWith = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InRange = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotNull = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Null = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HasChilds = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HasNoChilds = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InAudience = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Approximately = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ApproximatelyField = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InRangeField = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LastWeek = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LastMonth = 28,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NextWeek = 29,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NextMonth = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotEquals = 31,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotEqualsField = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ItemNotInSet = 33,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HasUnarchivedChilds = 34,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HasNoUnarchivedChilds = 35,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        All = 36,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SynonymXmlField", Namespace="http://Compano.com/Modules/ICS")]
    public enum SynonymXmlField : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ClassCode = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ClassCodeAndDescription = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ClassGroupCode = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ClassGroupName = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ClassName = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ConstantNow = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ConstantText = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ConstantToday = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LanguageCode = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Text = 9,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SynonymFilterField", Namespace="http://Compano.com/Modules/ICS")]
    public enum SynonymFilterField : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Class = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ClassCode = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ClassGroupCode = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ClassGroupName = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ClassName = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ConstantNow = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ConstantToday = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Language = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LanguageCode = 8,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://Compano.com/Modules/ICS", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Facet", Namespace="http://Compano.com/Modules/ICS")]
    [System.SerializableAttribute()]
    public partial class Facet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        private bool IsSelectedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Demo.ClientICSSynonym.FacetItem[] ItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Demo.ClientICSSynonym.FacetItem SelectedItemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool IsSelected {
            get {
                return this.IsSelectedField;
            }
            set {
                if ((this.IsSelectedField.Equals(value) != true)) {
                    this.IsSelectedField = value;
                    this.RaisePropertyChanged("IsSelected");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Demo.ClientICSSynonym.FacetItem[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Demo.ClientICSSynonym.FacetItem SelectedItem {
            get {
                return this.SelectedItemField;
            }
            set {
                if ((object.ReferenceEquals(this.SelectedItemField, value) != true)) {
                    this.SelectedItemField = value;
                    this.RaisePropertyChanged("SelectedItem");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FacetItem", Namespace="http://Compano.com/Modules/ICS")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientICSSynonym.SynonymViewOption))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientICSSynonym.FilterElement[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientICSSynonym.FilterElement))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientICSSynonym.ConditionTypeOption))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientICSSynonym.SynonymXmlField[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientICSSynonym.SynonymXmlField))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientICSSynonym.SynonymFilterField[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientICSSynonym.SynonymFilterField))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientICSSynonym.ArrayOfString))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientICSSynonym.Facet))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientICSSynonym.FacetItem[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientICSSynonym.Facet[]))]
    public partial class FacetItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        private int RecordCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object KeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RecordCount {
            get {
                return this.RecordCountField;
            }
            set {
                if ((this.RecordCountField.Equals(value) != true)) {
                    this.RecordCountField = value;
                    this.RaisePropertyChanged("RecordCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Unit {
            get {
                return this.UnitField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitField, value) != true)) {
                    this.UnitField = value;
                    this.RaisePropertyChanged("Unit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public object Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Compano.com/Modules/ICS", ConfigurationName="ClientICSSynonym.SynonymServiceSoap")]
    public interface SynonymServiceSoap {
        
        // CODEGEN: Generating message contract since element name sessionHandle from namespace http://Compano.com/Modules/ICS is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Compano.com/Modules/ICS/SetDefaultView", ReplyAction="*")]
        Demo.ClientICSSynonym.SetDefaultViewResponse SetDefaultView(Demo.ClientICSSynonym.SetDefaultViewRequest request);
        
        // CODEGEN: Generating message contract since element name sessionHandle from namespace http://Compano.com/Modules/ICS is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Compano.com/Modules/ICS/SelectAsJSON", ReplyAction="*")]
        Demo.ClientICSSynonym.SelectAsJSONResponse SelectAsJSON(Demo.ClientICSSynonym.SelectAsJSONRequest request);
        
        // CODEGEN: Generating message contract since element name sessionHandle from namespace http://Compano.com/Modules/ICS is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Compano.com/Modules/ICS/Select", ReplyAction="*")]
        Demo.ClientICSSynonym.SelectResponse Select(Demo.ClientICSSynonym.SelectRequest request);
        
        // CODEGEN: Generating message contract since element name sessionHandle from namespace http://Compano.com/Modules/ICS is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Compano.com/Modules/ICS/GetGridUrl", ReplyAction="*")]
        Demo.ClientICSSynonym.GetGridUrlResponse GetGridUrl(Demo.ClientICSSynonym.GetGridUrlRequest request);
        
        // CODEGEN: Generating message contract since element name sessionHandle from namespace http://Compano.com/Modules/ICS is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Compano.com/Modules/ICS/GetViewAsXml", ReplyAction="*")]
        Demo.ClientICSSynonym.GetViewAsXmlResponse GetViewAsXml(Demo.ClientICSSynonym.GetViewAsXmlRequest request);
        
        // CODEGEN: Generating message contract since element name sessionHandle from namespace http://Compano.com/Modules/ICS is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Compano.com/Modules/ICS/SetViewFilter", ReplyAction="*")]
        Demo.ClientICSSynonym.SetViewFilterResponse SetViewFilter(Demo.ClientICSSynonym.SetViewFilterRequest request);
        
        // CODEGEN: Generating message contract since element name sessionHandle from namespace http://Compano.com/Modules/ICS is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Compano.com/Modules/ICS/SetViewSortOrder", ReplyAction="*")]
        Demo.ClientICSSynonym.SetViewSortOrderResponse SetViewSortOrder(Demo.ClientICSSynonym.SetViewSortOrderRequest request);
        
        // CODEGEN: Generating message contract since element name sessionHandle from namespace http://Compano.com/Modules/ICS is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Compano.com/Modules/ICS/GetViewCount", ReplyAction="*")]
        Demo.ClientICSSynonym.GetViewCountResponse GetViewCount(Demo.ClientICSSynonym.GetViewCountRequest request);
        
        // CODEGEN: Generating message contract since element name sessionHandle from namespace http://Compano.com/Modules/ICS is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Compano.com/Modules/ICS/ResetViewFilter", ReplyAction="*")]
        Demo.ClientICSSynonym.ResetViewFilterResponse ResetViewFilter(Demo.ClientICSSynonym.ResetViewFilterRequest request);
        
        // CODEGEN: Generating message contract since element name sessionHandle from namespace http://Compano.com/Modules/ICS is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Compano.com/Modules/ICS/SetViewAdvancedFilter", ReplyAction="*")]
        Demo.ClientICSSynonym.SetViewAdvancedFilterResponse SetViewAdvancedFilter(Demo.ClientICSSynonym.SetViewAdvancedFilterRequest request);
        
        // CODEGEN: Generating message contract since element name sessionHandle from namespace http://Compano.com/Modules/ICS is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Compano.com/Modules/ICS/SetViewSearchText", ReplyAction="*")]
        Demo.ClientICSSynonym.SetViewSearchTextResponse SetViewSearchText(Demo.ClientICSSynonym.SetViewSearchTextRequest request);
        
        // CODEGEN: Generating message contract since element name sessionHandle from namespace http://Compano.com/Modules/ICS is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Compano.com/Modules/ICS/SetViewFacet", ReplyAction="*")]
        Demo.ClientICSSynonym.SetViewFacetResponse SetViewFacet(Demo.ClientICSSynonym.SetViewFacetRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetDefaultViewRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetDefaultView", Namespace="http://Compano.com/Modules/ICS", Order=0)]
        public Demo.ClientICSSynonym.SetDefaultViewRequestBody Body;
        
        public SetDefaultViewRequest() {
        }
        
        public SetDefaultViewRequest(Demo.ClientICSSynonym.SetDefaultViewRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/ICS")]
    public partial class SetDefaultViewRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionHandle;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public Demo.ClientICSSynonym.SynonymViewOption view;
        
        public SetDefaultViewRequestBody() {
        }
        
        public SetDefaultViewRequestBody(string sessionHandle, Demo.ClientICSSynonym.SynonymViewOption view) {
            this.sessionHandle = sessionHandle;
            this.view = view;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetDefaultViewResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetDefaultViewResponse", Namespace="http://Compano.com/Modules/ICS", Order=0)]
        public Demo.ClientICSSynonym.SetDefaultViewResponseBody Body;
        
        public SetDefaultViewResponse() {
        }
        
        public SetDefaultViewResponse(Demo.ClientICSSynonym.SetDefaultViewResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/ICS")]
    public partial class SetDefaultViewResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SetDefaultViewResult;
        
        public SetDefaultViewResponseBody() {
        }
        
        public SetDefaultViewResponseBody(string SetDefaultViewResult) {
            this.SetDefaultViewResult = SetDefaultViewResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAsJSONRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectAsJSON", Namespace="http://Compano.com/Modules/ICS", Order=0)]
        public Demo.ClientICSSynonym.SelectAsJSONRequestBody Body;
        
        public SelectAsJSONRequest() {
        }
        
        public SelectAsJSONRequest(Demo.ClientICSSynonym.SelectAsJSONRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/ICS")]
    public partial class SelectAsJSONRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionHandle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Demo.ClientICSSynonym.FilterElement[] filterElements;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Demo.ClientICSSynonym.SynonymXmlField[] fields;
        
        public SelectAsJSONRequestBody() {
        }
        
        public SelectAsJSONRequestBody(string sessionHandle, Demo.ClientICSSynonym.FilterElement[] filterElements, Demo.ClientICSSynonym.SynonymXmlField[] fields) {
            this.sessionHandle = sessionHandle;
            this.filterElements = filterElements;
            this.fields = fields;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAsJSONResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectAsJSONResponse", Namespace="http://Compano.com/Modules/ICS", Order=0)]
        public Demo.ClientICSSynonym.SelectAsJSONResponseBody Body;
        
        public SelectAsJSONResponse() {
        }
        
        public SelectAsJSONResponse(Demo.ClientICSSynonym.SelectAsJSONResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/ICS")]
    public partial class SelectAsJSONResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SelectAsJSONResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string json;
        
        public SelectAsJSONResponseBody() {
        }
        
        public SelectAsJSONResponseBody(string SelectAsJSONResult, string json) {
            this.SelectAsJSONResult = SelectAsJSONResult;
            this.json = json;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Select", Namespace="http://Compano.com/Modules/ICS", Order=0)]
        public Demo.ClientICSSynonym.SelectRequestBody Body;
        
        public SelectRequest() {
        }
        
        public SelectRequest(Demo.ClientICSSynonym.SelectRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/ICS")]
    public partial class SelectRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionHandle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Demo.ClientICSSynonym.SynonymFilterField[] filterFields;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Demo.ClientICSSynonym.ArrayOfString filterValues;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string searchText;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public Demo.ClientICSSynonym.SynonymXmlField[] fields;
        
        public SelectRequestBody() {
        }
        
        public SelectRequestBody(string sessionHandle, Demo.ClientICSSynonym.SynonymFilterField[] filterFields, Demo.ClientICSSynonym.ArrayOfString filterValues, string searchText, Demo.ClientICSSynonym.SynonymXmlField[] fields) {
            this.sessionHandle = sessionHandle;
            this.filterFields = filterFields;
            this.filterValues = filterValues;
            this.searchText = searchText;
            this.fields = fields;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectResponse", Namespace="http://Compano.com/Modules/ICS", Order=0)]
        public Demo.ClientICSSynonym.SelectResponseBody Body;
        
        public SelectResponse() {
        }
        
        public SelectResponse(Demo.ClientICSSynonym.SelectResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/ICS")]
    public partial class SelectResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SelectResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string xml;
        
        public SelectResponseBody() {
        }
        
        public SelectResponseBody(string SelectResult, string xml) {
            this.SelectResult = SelectResult;
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGridUrlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGridUrl", Namespace="http://Compano.com/Modules/ICS", Order=0)]
        public Demo.ClientICSSynonym.GetGridUrlRequestBody Body;
        
        public GetGridUrlRequest() {
        }
        
        public GetGridUrlRequest(Demo.ClientICSSynonym.GetGridUrlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/ICS")]
    public partial class GetGridUrlRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionHandle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Demo.ClientICSSynonym.SynonymFilterField[] filterFields;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Demo.ClientICSSynonym.ArrayOfString filterValues;
        
        public GetGridUrlRequestBody() {
        }
        
        public GetGridUrlRequestBody(string sessionHandle, Demo.ClientICSSynonym.SynonymFilterField[] filterFields, Demo.ClientICSSynonym.ArrayOfString filterValues) {
            this.sessionHandle = sessionHandle;
            this.filterFields = filterFields;
            this.filterValues = filterValues;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGridUrlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGridUrlResponse", Namespace="http://Compano.com/Modules/ICS", Order=0)]
        public Demo.ClientICSSynonym.GetGridUrlResponseBody Body;
        
        public GetGridUrlResponse() {
        }
        
        public GetGridUrlResponse(Demo.ClientICSSynonym.GetGridUrlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/ICS")]
    public partial class GetGridUrlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetGridUrlResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string url;
        
        public GetGridUrlResponseBody() {
        }
        
        public GetGridUrlResponseBody(string GetGridUrlResult, string url) {
            this.GetGridUrlResult = GetGridUrlResult;
            this.url = url;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetViewAsXmlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetViewAsXml", Namespace="http://Compano.com/Modules/ICS", Order=0)]
        public Demo.ClientICSSynonym.GetViewAsXmlRequestBody Body;
        
        public GetViewAsXmlRequest() {
        }
        
        public GetViewAsXmlRequest(Demo.ClientICSSynonym.GetViewAsXmlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/ICS")]
    public partial class GetViewAsXmlRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionHandle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Demo.ClientICSSynonym.SynonymXmlField[] fields;
        
        public GetViewAsXmlRequestBody() {
        }
        
        public GetViewAsXmlRequestBody(string sessionHandle, Demo.ClientICSSynonym.SynonymXmlField[] fields) {
            this.sessionHandle = sessionHandle;
            this.fields = fields;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetViewAsXmlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetViewAsXmlResponse", Namespace="http://Compano.com/Modules/ICS", Order=0)]
        public Demo.ClientICSSynonym.GetViewAsXmlResponseBody Body;
        
        public GetViewAsXmlResponse() {
        }
        
        public GetViewAsXmlResponse(Demo.ClientICSSynonym.GetViewAsXmlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/ICS")]
    public partial class GetViewAsXmlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetViewAsXmlResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string xml;
        
        public GetViewAsXmlResponseBody() {
        }
        
        public GetViewAsXmlResponseBody(string GetViewAsXmlResult, string xml) {
            this.GetViewAsXmlResult = GetViewAsXmlResult;
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetViewFilterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetViewFilter", Namespace="http://Compano.com/Modules/ICS", Order=0)]
        public Demo.ClientICSSynonym.SetViewFilterRequestBody Body;
        
        public SetViewFilterRequest() {
        }
        
        public SetViewFilterRequest(Demo.ClientICSSynonym.SetViewFilterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/ICS")]
    public partial class SetViewFilterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionHandle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Demo.ClientICSSynonym.SynonymFilterField[] filterFields;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Demo.ClientICSSynonym.ArrayOfString filterValues;
        
        public SetViewFilterRequestBody() {
        }
        
        public SetViewFilterRequestBody(string sessionHandle, Demo.ClientICSSynonym.SynonymFilterField[] filterFields, Demo.ClientICSSynonym.ArrayOfString filterValues) {
            this.sessionHandle = sessionHandle;
            this.filterFields = filterFields;
            this.filterValues = filterValues;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetViewFilterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetViewFilterResponse", Namespace="http://Compano.com/Modules/ICS", Order=0)]
        public Demo.ClientICSSynonym.SetViewFilterResponseBody Body;
        
        public SetViewFilterResponse() {
        }
        
        public SetViewFilterResponse(Demo.ClientICSSynonym.SetViewFilterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/ICS")]
    public partial class SetViewFilterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SetViewFilterResult;
        
        public SetViewFilterResponseBody() {
        }
        
        public SetViewFilterResponseBody(string SetViewFilterResult) {
            this.SetViewFilterResult = SetViewFilterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetViewSortOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetViewSortOrder", Namespace="http://Compano.com/Modules/ICS", Order=0)]
        public Demo.ClientICSSynonym.SetViewSortOrderRequestBody Body;
        
        public SetViewSortOrderRequest() {
        }
        
        public SetViewSortOrderRequest(Demo.ClientICSSynonym.SetViewSortOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/ICS")]
    public partial class SetViewSortOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionHandle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sortExpression;
        
        public SetViewSortOrderRequestBody() {
        }
        
        public SetViewSortOrderRequestBody(string sessionHandle, string sortExpression) {
            this.sessionHandle = sessionHandle;
            this.sortExpression = sortExpression;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetViewSortOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetViewSortOrderResponse", Namespace="http://Compano.com/Modules/ICS", Order=0)]
        public Demo.ClientICSSynonym.SetViewSortOrderResponseBody Body;
        
        public SetViewSortOrderResponse() {
        }
        
        public SetViewSortOrderResponse(Demo.ClientICSSynonym.SetViewSortOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/ICS")]
    public partial class SetViewSortOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SetViewSortOrderResult;
        
        public SetViewSortOrderResponseBody() {
        }
        
        public SetViewSortOrderResponseBody(string SetViewSortOrderResult) {
            this.SetViewSortOrderResult = SetViewSortOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetViewCountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetViewCount", Namespace="http://Compano.com/Modules/ICS", Order=0)]
        public Demo.ClientICSSynonym.GetViewCountRequestBody Body;
        
        public GetViewCountRequest() {
        }
        
        public GetViewCountRequest(Demo.ClientICSSynonym.GetViewCountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/ICS")]
    public partial class GetViewCountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionHandle;
        
        public GetViewCountRequestBody() {
        }
        
        public GetViewCountRequestBody(string sessionHandle) {
            this.sessionHandle = sessionHandle;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetViewCountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetViewCountResponse", Namespace="http://Compano.com/Modules/ICS", Order=0)]
        public Demo.ClientICSSynonym.GetViewCountResponseBody Body;
        
        public GetViewCountResponse() {
        }
        
        public GetViewCountResponse(Demo.ClientICSSynonym.GetViewCountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/ICS")]
    public partial class GetViewCountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetViewCountResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int recordCount;
        
        public GetViewCountResponseBody() {
        }
        
        public GetViewCountResponseBody(string GetViewCountResult, int recordCount) {
            this.GetViewCountResult = GetViewCountResult;
            this.recordCount = recordCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResetViewFilterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResetViewFilter", Namespace="http://Compano.com/Modules/ICS", Order=0)]
        public Demo.ClientICSSynonym.ResetViewFilterRequestBody Body;
        
        public ResetViewFilterRequest() {
        }
        
        public ResetViewFilterRequest(Demo.ClientICSSynonym.ResetViewFilterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/ICS")]
    public partial class ResetViewFilterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionHandle;
        
        public ResetViewFilterRequestBody() {
        }
        
        public ResetViewFilterRequestBody(string sessionHandle) {
            this.sessionHandle = sessionHandle;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResetViewFilterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResetViewFilterResponse", Namespace="http://Compano.com/Modules/ICS", Order=0)]
        public Demo.ClientICSSynonym.ResetViewFilterResponseBody Body;
        
        public ResetViewFilterResponse() {
        }
        
        public ResetViewFilterResponse(Demo.ClientICSSynonym.ResetViewFilterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/ICS")]
    public partial class ResetViewFilterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ResetViewFilterResult;
        
        public ResetViewFilterResponseBody() {
        }
        
        public ResetViewFilterResponseBody(string ResetViewFilterResult) {
            this.ResetViewFilterResult = ResetViewFilterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetViewAdvancedFilterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetViewAdvancedFilter", Namespace="http://Compano.com/Modules/ICS", Order=0)]
        public Demo.ClientICSSynonym.SetViewAdvancedFilterRequestBody Body;
        
        public SetViewAdvancedFilterRequest() {
        }
        
        public SetViewAdvancedFilterRequest(Demo.ClientICSSynonym.SetViewAdvancedFilterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/ICS")]
    public partial class SetViewAdvancedFilterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionHandle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Demo.ClientICSSynonym.FilterElement[] filterElements;
        
        public SetViewAdvancedFilterRequestBody() {
        }
        
        public SetViewAdvancedFilterRequestBody(string sessionHandle, Demo.ClientICSSynonym.FilterElement[] filterElements) {
            this.sessionHandle = sessionHandle;
            this.filterElements = filterElements;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetViewAdvancedFilterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetViewAdvancedFilterResponse", Namespace="http://Compano.com/Modules/ICS", Order=0)]
        public Demo.ClientICSSynonym.SetViewAdvancedFilterResponseBody Body;
        
        public SetViewAdvancedFilterResponse() {
        }
        
        public SetViewAdvancedFilterResponse(Demo.ClientICSSynonym.SetViewAdvancedFilterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/ICS")]
    public partial class SetViewAdvancedFilterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SetViewAdvancedFilterResult;
        
        public SetViewAdvancedFilterResponseBody() {
        }
        
        public SetViewAdvancedFilterResponseBody(string SetViewAdvancedFilterResult) {
            this.SetViewAdvancedFilterResult = SetViewAdvancedFilterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetViewSearchTextRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetViewSearchText", Namespace="http://Compano.com/Modules/ICS", Order=0)]
        public Demo.ClientICSSynonym.SetViewSearchTextRequestBody Body;
        
        public SetViewSearchTextRequest() {
        }
        
        public SetViewSearchTextRequest(Demo.ClientICSSynonym.SetViewSearchTextRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/ICS")]
    public partial class SetViewSearchTextRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionHandle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string searchText;
        
        public SetViewSearchTextRequestBody() {
        }
        
        public SetViewSearchTextRequestBody(string sessionHandle, string searchText) {
            this.sessionHandle = sessionHandle;
            this.searchText = searchText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetViewSearchTextResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetViewSearchTextResponse", Namespace="http://Compano.com/Modules/ICS", Order=0)]
        public Demo.ClientICSSynonym.SetViewSearchTextResponseBody Body;
        
        public SetViewSearchTextResponse() {
        }
        
        public SetViewSearchTextResponse(Demo.ClientICSSynonym.SetViewSearchTextResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/ICS")]
    public partial class SetViewSearchTextResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SetViewSearchTextResult;
        
        public SetViewSearchTextResponseBody() {
        }
        
        public SetViewSearchTextResponseBody(string SetViewSearchTextResult) {
            this.SetViewSearchTextResult = SetViewSearchTextResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetViewFacetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetViewFacet", Namespace="http://Compano.com/Modules/ICS", Order=0)]
        public Demo.ClientICSSynonym.SetViewFacetRequestBody Body;
        
        public SetViewFacetRequest() {
        }
        
        public SetViewFacetRequest(Demo.ClientICSSynonym.SetViewFacetRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/ICS")]
    public partial class SetViewFacetRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionHandle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string selectedFacetItem;
        
        public SetViewFacetRequestBody() {
        }
        
        public SetViewFacetRequestBody(string sessionHandle, string selectedFacetItem) {
            this.sessionHandle = sessionHandle;
            this.selectedFacetItem = selectedFacetItem;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetViewFacetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetViewFacetResponse", Namespace="http://Compano.com/Modules/ICS", Order=0)]
        public Demo.ClientICSSynonym.SetViewFacetResponseBody Body;
        
        public SetViewFacetResponse() {
        }
        
        public SetViewFacetResponse(Demo.ClientICSSynonym.SetViewFacetResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/ICS")]
    public partial class SetViewFacetResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SetViewFacetResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Demo.ClientICSSynonym.Facet[] facets;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int recordCount;
        
        public SetViewFacetResponseBody() {
        }
        
        public SetViewFacetResponseBody(string SetViewFacetResult, Demo.ClientICSSynonym.Facet[] facets, int recordCount) {
            this.SetViewFacetResult = SetViewFacetResult;
            this.facets = facets;
            this.recordCount = recordCount;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SynonymServiceSoapChannel : Demo.ClientICSSynonym.SynonymServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SynonymServiceSoapClient : System.ServiceModel.ClientBase<Demo.ClientICSSynonym.SynonymServiceSoap>, Demo.ClientICSSynonym.SynonymServiceSoap {
        
        public SynonymServiceSoapClient() {
        }
        
        public SynonymServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SynonymServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SynonymServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SynonymServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.ClientICSSynonym.SetDefaultViewResponse Demo.ClientICSSynonym.SynonymServiceSoap.SetDefaultView(Demo.ClientICSSynonym.SetDefaultViewRequest request) {
            return base.Channel.SetDefaultView(request);
        }
        
        public string SetDefaultView(string sessionHandle, Demo.ClientICSSynonym.SynonymViewOption view) {
            Demo.ClientICSSynonym.SetDefaultViewRequest inValue = new Demo.ClientICSSynonym.SetDefaultViewRequest();
            inValue.Body = new Demo.ClientICSSynonym.SetDefaultViewRequestBody();
            inValue.Body.sessionHandle = sessionHandle;
            inValue.Body.view = view;
            Demo.ClientICSSynonym.SetDefaultViewResponse retVal = ((Demo.ClientICSSynonym.SynonymServiceSoap)(this)).SetDefaultView(inValue);
            return retVal.Body.SetDefaultViewResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.ClientICSSynonym.SelectAsJSONResponse Demo.ClientICSSynonym.SynonymServiceSoap.SelectAsJSON(Demo.ClientICSSynonym.SelectAsJSONRequest request) {
            return base.Channel.SelectAsJSON(request);
        }
        
        public string SelectAsJSON(string sessionHandle, Demo.ClientICSSynonym.FilterElement[] filterElements, Demo.ClientICSSynonym.SynonymXmlField[] fields, out string json) {
            Demo.ClientICSSynonym.SelectAsJSONRequest inValue = new Demo.ClientICSSynonym.SelectAsJSONRequest();
            inValue.Body = new Demo.ClientICSSynonym.SelectAsJSONRequestBody();
            inValue.Body.sessionHandle = sessionHandle;
            inValue.Body.filterElements = filterElements;
            inValue.Body.fields = fields;
            Demo.ClientICSSynonym.SelectAsJSONResponse retVal = ((Demo.ClientICSSynonym.SynonymServiceSoap)(this)).SelectAsJSON(inValue);
            json = retVal.Body.json;
            return retVal.Body.SelectAsJSONResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.ClientICSSynonym.SelectResponse Demo.ClientICSSynonym.SynonymServiceSoap.Select(Demo.ClientICSSynonym.SelectRequest request) {
            return base.Channel.Select(request);
        }
        
        public string Select(string sessionHandle, Demo.ClientICSSynonym.SynonymFilterField[] filterFields, Demo.ClientICSSynonym.ArrayOfString filterValues, string searchText, Demo.ClientICSSynonym.SynonymXmlField[] fields, out string xml) {
            Demo.ClientICSSynonym.SelectRequest inValue = new Demo.ClientICSSynonym.SelectRequest();
            inValue.Body = new Demo.ClientICSSynonym.SelectRequestBody();
            inValue.Body.sessionHandle = sessionHandle;
            inValue.Body.filterFields = filterFields;
            inValue.Body.filterValues = filterValues;
            inValue.Body.searchText = searchText;
            inValue.Body.fields = fields;
            Demo.ClientICSSynonym.SelectResponse retVal = ((Demo.ClientICSSynonym.SynonymServiceSoap)(this)).Select(inValue);
            xml = retVal.Body.xml;
            return retVal.Body.SelectResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.ClientICSSynonym.GetGridUrlResponse Demo.ClientICSSynonym.SynonymServiceSoap.GetGridUrl(Demo.ClientICSSynonym.GetGridUrlRequest request) {
            return base.Channel.GetGridUrl(request);
        }
        
        public string GetGridUrl(string sessionHandle, Demo.ClientICSSynonym.SynonymFilterField[] filterFields, Demo.ClientICSSynonym.ArrayOfString filterValues, out string url) {
            Demo.ClientICSSynonym.GetGridUrlRequest inValue = new Demo.ClientICSSynonym.GetGridUrlRequest();
            inValue.Body = new Demo.ClientICSSynonym.GetGridUrlRequestBody();
            inValue.Body.sessionHandle = sessionHandle;
            inValue.Body.filterFields = filterFields;
            inValue.Body.filterValues = filterValues;
            Demo.ClientICSSynonym.GetGridUrlResponse retVal = ((Demo.ClientICSSynonym.SynonymServiceSoap)(this)).GetGridUrl(inValue);
            url = retVal.Body.url;
            return retVal.Body.GetGridUrlResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.ClientICSSynonym.GetViewAsXmlResponse Demo.ClientICSSynonym.SynonymServiceSoap.GetViewAsXml(Demo.ClientICSSynonym.GetViewAsXmlRequest request) {
            return base.Channel.GetViewAsXml(request);
        }
        
        public string GetViewAsXml(string sessionHandle, Demo.ClientICSSynonym.SynonymXmlField[] fields, out string xml) {
            Demo.ClientICSSynonym.GetViewAsXmlRequest inValue = new Demo.ClientICSSynonym.GetViewAsXmlRequest();
            inValue.Body = new Demo.ClientICSSynonym.GetViewAsXmlRequestBody();
            inValue.Body.sessionHandle = sessionHandle;
            inValue.Body.fields = fields;
            Demo.ClientICSSynonym.GetViewAsXmlResponse retVal = ((Demo.ClientICSSynonym.SynonymServiceSoap)(this)).GetViewAsXml(inValue);
            xml = retVal.Body.xml;
            return retVal.Body.GetViewAsXmlResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.ClientICSSynonym.SetViewFilterResponse Demo.ClientICSSynonym.SynonymServiceSoap.SetViewFilter(Demo.ClientICSSynonym.SetViewFilterRequest request) {
            return base.Channel.SetViewFilter(request);
        }
        
        public string SetViewFilter(string sessionHandle, Demo.ClientICSSynonym.SynonymFilterField[] filterFields, Demo.ClientICSSynonym.ArrayOfString filterValues) {
            Demo.ClientICSSynonym.SetViewFilterRequest inValue = new Demo.ClientICSSynonym.SetViewFilterRequest();
            inValue.Body = new Demo.ClientICSSynonym.SetViewFilterRequestBody();
            inValue.Body.sessionHandle = sessionHandle;
            inValue.Body.filterFields = filterFields;
            inValue.Body.filterValues = filterValues;
            Demo.ClientICSSynonym.SetViewFilterResponse retVal = ((Demo.ClientICSSynonym.SynonymServiceSoap)(this)).SetViewFilter(inValue);
            return retVal.Body.SetViewFilterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.ClientICSSynonym.SetViewSortOrderResponse Demo.ClientICSSynonym.SynonymServiceSoap.SetViewSortOrder(Demo.ClientICSSynonym.SetViewSortOrderRequest request) {
            return base.Channel.SetViewSortOrder(request);
        }
        
        public string SetViewSortOrder(string sessionHandle, string sortExpression) {
            Demo.ClientICSSynonym.SetViewSortOrderRequest inValue = new Demo.ClientICSSynonym.SetViewSortOrderRequest();
            inValue.Body = new Demo.ClientICSSynonym.SetViewSortOrderRequestBody();
            inValue.Body.sessionHandle = sessionHandle;
            inValue.Body.sortExpression = sortExpression;
            Demo.ClientICSSynonym.SetViewSortOrderResponse retVal = ((Demo.ClientICSSynonym.SynonymServiceSoap)(this)).SetViewSortOrder(inValue);
            return retVal.Body.SetViewSortOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.ClientICSSynonym.GetViewCountResponse Demo.ClientICSSynonym.SynonymServiceSoap.GetViewCount(Demo.ClientICSSynonym.GetViewCountRequest request) {
            return base.Channel.GetViewCount(request);
        }
        
        public string GetViewCount(string sessionHandle, out int recordCount) {
            Demo.ClientICSSynonym.GetViewCountRequest inValue = new Demo.ClientICSSynonym.GetViewCountRequest();
            inValue.Body = new Demo.ClientICSSynonym.GetViewCountRequestBody();
            inValue.Body.sessionHandle = sessionHandle;
            Demo.ClientICSSynonym.GetViewCountResponse retVal = ((Demo.ClientICSSynonym.SynonymServiceSoap)(this)).GetViewCount(inValue);
            recordCount = retVal.Body.recordCount;
            return retVal.Body.GetViewCountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.ClientICSSynonym.ResetViewFilterResponse Demo.ClientICSSynonym.SynonymServiceSoap.ResetViewFilter(Demo.ClientICSSynonym.ResetViewFilterRequest request) {
            return base.Channel.ResetViewFilter(request);
        }
        
        public string ResetViewFilter(string sessionHandle) {
            Demo.ClientICSSynonym.ResetViewFilterRequest inValue = new Demo.ClientICSSynonym.ResetViewFilterRequest();
            inValue.Body = new Demo.ClientICSSynonym.ResetViewFilterRequestBody();
            inValue.Body.sessionHandle = sessionHandle;
            Demo.ClientICSSynonym.ResetViewFilterResponse retVal = ((Demo.ClientICSSynonym.SynonymServiceSoap)(this)).ResetViewFilter(inValue);
            return retVal.Body.ResetViewFilterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.ClientICSSynonym.SetViewAdvancedFilterResponse Demo.ClientICSSynonym.SynonymServiceSoap.SetViewAdvancedFilter(Demo.ClientICSSynonym.SetViewAdvancedFilterRequest request) {
            return base.Channel.SetViewAdvancedFilter(request);
        }
        
        public string SetViewAdvancedFilter(string sessionHandle, Demo.ClientICSSynonym.FilterElement[] filterElements) {
            Demo.ClientICSSynonym.SetViewAdvancedFilterRequest inValue = new Demo.ClientICSSynonym.SetViewAdvancedFilterRequest();
            inValue.Body = new Demo.ClientICSSynonym.SetViewAdvancedFilterRequestBody();
            inValue.Body.sessionHandle = sessionHandle;
            inValue.Body.filterElements = filterElements;
            Demo.ClientICSSynonym.SetViewAdvancedFilterResponse retVal = ((Demo.ClientICSSynonym.SynonymServiceSoap)(this)).SetViewAdvancedFilter(inValue);
            return retVal.Body.SetViewAdvancedFilterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.ClientICSSynonym.SetViewSearchTextResponse Demo.ClientICSSynonym.SynonymServiceSoap.SetViewSearchText(Demo.ClientICSSynonym.SetViewSearchTextRequest request) {
            return base.Channel.SetViewSearchText(request);
        }
        
        public string SetViewSearchText(string sessionHandle, string searchText) {
            Demo.ClientICSSynonym.SetViewSearchTextRequest inValue = new Demo.ClientICSSynonym.SetViewSearchTextRequest();
            inValue.Body = new Demo.ClientICSSynonym.SetViewSearchTextRequestBody();
            inValue.Body.sessionHandle = sessionHandle;
            inValue.Body.searchText = searchText;
            Demo.ClientICSSynonym.SetViewSearchTextResponse retVal = ((Demo.ClientICSSynonym.SynonymServiceSoap)(this)).SetViewSearchText(inValue);
            return retVal.Body.SetViewSearchTextResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.ClientICSSynonym.SetViewFacetResponse Demo.ClientICSSynonym.SynonymServiceSoap.SetViewFacet(Demo.ClientICSSynonym.SetViewFacetRequest request) {
            return base.Channel.SetViewFacet(request);
        }
        
        public string SetViewFacet(string sessionHandle, string selectedFacetItem, out Demo.ClientICSSynonym.Facet[] facets, out int recordCount) {
            Demo.ClientICSSynonym.SetViewFacetRequest inValue = new Demo.ClientICSSynonym.SetViewFacetRequest();
            inValue.Body = new Demo.ClientICSSynonym.SetViewFacetRequestBody();
            inValue.Body.sessionHandle = sessionHandle;
            inValue.Body.selectedFacetItem = selectedFacetItem;
            Demo.ClientICSSynonym.SetViewFacetResponse retVal = ((Demo.ClientICSSynonym.SynonymServiceSoap)(this)).SetViewFacet(inValue);
            facets = retVal.Body.facets;
            recordCount = retVal.Body.recordCount;
            return retVal.Body.SetViewFacetResult;
        }
    }
}
