//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Demo.tstRensaMessageService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://www.ketenstandaard.nl/WS/MessageService/3.0", ConfigurationName="tstRensaMessageService.IMessageService30")]
    public interface IMessageService30 {
        
        // CODEGEN: Generating message contract since the operation GetAvailableMessages is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="messageservice/GetAvailableMessages", ReplyAction="https://www.ketenstandaard.nl/WS/MessageService/3.0/IMessageService30/GetAvailabl" +
            "eMessagesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Demo.tstRensaMessageService.GetAvailableMessagesResponse GetAvailableMessages(Demo.tstRensaMessageService.GetAvailableMessagesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="messageservice/GetAvailableMessages", ReplyAction="https://www.ketenstandaard.nl/WS/MessageService/3.0/IMessageService30/GetAvailabl" +
            "eMessagesResponse")]
        System.IAsyncResult BeginGetAvailableMessages(Demo.tstRensaMessageService.GetAvailableMessagesRequest request, System.AsyncCallback callback, object asyncState);
        
        Demo.tstRensaMessageService.GetAvailableMessagesResponse EndGetAvailableMessages(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since the operation GetMessage is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="messageservice/GetMessage", ReplyAction="https://www.ketenstandaard.nl/WS/MessageService/3.0/IMessageService30/GetMessageR" +
            "esponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Demo.tstRensaMessageService.GetMessageResponse GetMessage(Demo.tstRensaMessageService.GetMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="messageservice/GetMessage", ReplyAction="https://www.ketenstandaard.nl/WS/MessageService/3.0/IMessageService30/GetMessageR" +
            "esponse")]
        System.IAsyncResult BeginGetMessage(Demo.tstRensaMessageService.GetMessageRequest request, System.AsyncCallback callback, object asyncState);
        
        Demo.tstRensaMessageService.GetMessageResponse EndGetMessage(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since the operation DeleteMessage is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="messageservice/DeleteMessage", ReplyAction="https://www.ketenstandaard.nl/WS/MessageService/3.0/IMessageService30/DeleteMessa" +
            "geResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Demo.tstRensaMessageService.DeleteMessageResponse DeleteMessage(Demo.tstRensaMessageService.DeleteMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="messageservice/DeleteMessage", ReplyAction="https://www.ketenstandaard.nl/WS/MessageService/3.0/IMessageService30/DeleteMessa" +
            "geResponse")]
        System.IAsyncResult BeginDeleteMessage(Demo.tstRensaMessageService.DeleteMessageRequest request, System.AsyncCallback callback, object asyncState);
        
        Demo.tstRensaMessageService.DeleteMessageResponse EndDeleteMessage(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since the operation PostMessage is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="messageservice/PostMessage", ReplyAction="https://www.ketenstandaard.nl/WS/MessageService/3.0/IMessageService30/PostMessage" +
            "Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Demo.tstRensaMessageService.DeleteMessageResponse PostMessage(Demo.tstRensaMessageService.PostMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="messageservice/PostMessage", ReplyAction="https://www.ketenstandaard.nl/WS/MessageService/3.0/IMessageService30/PostMessage" +
            "Response")]
        System.IAsyncResult BeginPostMessage(Demo.tstRensaMessageService.PostMessageRequest request, System.AsyncCallback callback, object asyncState);
        
        Demo.tstRensaMessageService.DeleteMessageResponse EndPostMessage(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ketenstandaard.nl/WS/MessageService/3.0")]
    public partial class CustomInfoType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool isTestMessageField;
        
        private string languageCodeField;
        
        private System.Nullable<bool> isContentCompressedField;
        
        private string applicationIdField;
        
        private string versionIdField;
        
        private string relationIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool IsTestMessage {
            get {
                return this.isTestMessageField;
            }
            set {
                this.isTestMessageField = value;
                this.RaisePropertyChanged("IsTestMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string LanguageCode {
            get {
                return this.languageCodeField;
            }
            set {
                this.languageCodeField = value;
                this.RaisePropertyChanged("LanguageCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public System.Nullable<bool> IsContentCompressed {
            get {
                return this.isContentCompressedField;
            }
            set {
                this.isContentCompressedField = value;
                this.RaisePropertyChanged("IsContentCompressed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string ApplicationId {
            get {
                return this.applicationIdField;
            }
            set {
                this.applicationIdField = value;
                this.RaisePropertyChanged("ApplicationId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string VersionId {
            get {
                return this.versionIdField;
            }
            set {
                this.versionIdField = value;
                this.RaisePropertyChanged("VersionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string RelationId {
            get {
                return this.relationIdField;
            }
            set {
                this.relationIdField = value;
                this.RaisePropertyChanged("RelationId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ketenstandaard.nl/WS/MessageService/3.0")]
    public partial class MessageResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MessageType messageField;
        
        private bool messageResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public MessageType Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool MessageResult {
            get {
                return this.messageResultField;
            }
            set {
                this.messageResultField = value;
                this.RaisePropertyChanged("MessageResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ketenstandaard.nl/WS/MessageService/3.0")]
    public partial class MessageType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MessagePropertiesType msgPropertiesField;
        
        private string msgContentField;
        
        private AttachmentType[] attachmentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public MessagePropertiesType MsgProperties {
            get {
                return this.msgPropertiesField;
            }
            set {
                this.msgPropertiesField = value;
                this.RaisePropertyChanged("MsgProperties");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MsgContent {
            get {
                return this.msgContentField;
            }
            set {
                this.msgContentField = value;
                this.RaisePropertyChanged("MsgContent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Attachment", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public AttachmentType[] Attachment {
            get {
                return this.attachmentField;
            }
            set {
                this.attachmentField = value;
                this.RaisePropertyChanged("Attachment");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ketenstandaard.nl/WS/MessageService/3.0")]
    public partial class MessagePropertiesType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string msgIdField;
        
        private System.DateTime msgDateTimeField;
        
        private System.Nullable<MsgFormatType> msgFormatField;
        
        private string msgVersionField;
        
        private string msgTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string MsgId {
            get {
                return this.msgIdField;
            }
            set {
                this.msgIdField = value;
                this.RaisePropertyChanged("MsgId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime MsgDateTime {
            get {
                return this.msgDateTimeField;
            }
            set {
                this.msgDateTimeField = value;
                this.RaisePropertyChanged("MsgDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public System.Nullable<MsgFormatType> MsgFormat {
            get {
                return this.msgFormatField;
            }
            set {
                this.msgFormatField = value;
                this.RaisePropertyChanged("MsgFormat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string MsgVersion {
            get {
                return this.msgVersionField;
            }
            set {
                this.msgVersionField = value;
                this.RaisePropertyChanged("MsgVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string MsgType {
            get {
                return this.msgTypeField;
            }
            set {
                this.msgTypeField = value;
                this.RaisePropertyChanged("MsgType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ketenstandaard.nl/WS/MessageService/3.0")]
    public enum MsgFormatType {
        
        /// <remarks/>
        INSBOU,
        
        /// <remarks/>
        D96A,
        
        /// <remarks/>
        KETENSTANDAARD,
        
        /// <remarks/>
        CUSTOM,
        
        /// <remarks/>
        SALES,
        
        /// <remarks/>
        ETIM,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ketenstandaard.nl/WS/MessageService/3.0")]
    public partial class AttachmentType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string uRLField;
        
        private string documentTypeField;
        
        private string fileTypeField;
        
        private string fileNameField;
        
        private byte[] attachedDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
                this.RaisePropertyChanged("URL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string DocumentType {
            get {
                return this.documentTypeField;
            }
            set {
                this.documentTypeField = value;
                this.RaisePropertyChanged("DocumentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string FileType {
            get {
                return this.fileTypeField;
            }
            set {
                this.fileTypeField = value;
                this.RaisePropertyChanged("FileType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("FileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true, Order=4)]
        public byte[] AttachedData {
            get {
                return this.attachedDataField;
            }
            set {
                this.attachedDataField = value;
                this.RaisePropertyChanged("AttachedData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ketenstandaard.nl/WS/MessageService/3.0")]
    public partial class MessageRequestResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MessageType messageRequestResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public MessageType MessageRequestResult {
            get {
                return this.messageRequestResultField;
            }
            set {
                this.messageRequestResultField = value;
                this.RaisePropertyChanged("MessageRequestResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ketenstandaard.nl/WS/MessageService/3.0")]
    public partial class MessageRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string msgIdField;
        
        private System.Nullable<MsgFormatType> msgFormatField;
        
        private string msgVersionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string MsgId {
            get {
                return this.msgIdField;
            }
            set {
                this.msgIdField = value;
                this.RaisePropertyChanged("MsgId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public System.Nullable<MsgFormatType> MsgFormat {
            get {
                return this.msgFormatField;
            }
            set {
                this.msgFormatField = value;
                this.RaisePropertyChanged("MsgFormat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string MsgVersion {
            get {
                return this.msgVersionField;
            }
            set {
                this.msgVersionField = value;
                this.RaisePropertyChanged("MsgVersion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ketenstandaard.nl/WS/MessageService/3.0")]
    public partial class AvailableMessagesRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string msgTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string MsgType {
            get {
                return this.msgTypeField;
            }
            set {
                this.msgTypeField = value;
                this.RaisePropertyChanged("MsgType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAvailableMessagesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://www.ketenstandaard.nl/WS/MessageService/3.0")]
        public Demo.tstRensaMessageService.CustomInfoType CustomInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.ketenstandaard.nl/WS/MessageService/3.0", Order=0)]
        public Demo.tstRensaMessageService.AvailableMessagesRequestType AvailableMessagesRequest;
        
        public GetAvailableMessagesRequest() {
        }
        
        public GetAvailableMessagesRequest(Demo.tstRensaMessageService.CustomInfoType CustomInfo, Demo.tstRensaMessageService.AvailableMessagesRequestType AvailableMessagesRequest) {
            this.CustomInfo = CustomInfo;
            this.AvailableMessagesRequest = AvailableMessagesRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAvailableMessagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.ketenstandaard.nl/WS/MessageService/3.0", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("MessageList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Demo.tstRensaMessageService.MessagePropertiesType[] AvailableMessagesResponse;
        
        public GetAvailableMessagesResponse() {
        }
        
        public GetAvailableMessagesResponse(Demo.tstRensaMessageService.MessagePropertiesType[] AvailableMessagesResponse) {
            this.AvailableMessagesResponse = AvailableMessagesResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessageRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://www.ketenstandaard.nl/WS/MessageService/3.0")]
        public Demo.tstRensaMessageService.CustomInfoType CustomInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.ketenstandaard.nl/WS/MessageService/3.0", Order=0)]
        public Demo.tstRensaMessageService.MessageRequestType MessageRequest;
        
        public GetMessageRequest() {
        }
        
        public GetMessageRequest(Demo.tstRensaMessageService.CustomInfoType CustomInfo, Demo.tstRensaMessageService.MessageRequestType MessageRequest) {
            this.CustomInfo = CustomInfo;
            this.MessageRequest = MessageRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.ketenstandaard.nl/WS/MessageService/3.0", Order=0)]
        public Demo.tstRensaMessageService.MessageRequestResponseType MessageRequestResponse;
        
        public GetMessageResponse() {
        }
        
        public GetMessageResponse(Demo.tstRensaMessageService.MessageRequestResponseType MessageRequestResponse) {
            this.MessageRequestResponse = MessageRequestResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteMessageRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://www.ketenstandaard.nl/WS/MessageService/3.0")]
        public Demo.tstRensaMessageService.CustomInfoType CustomInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.ketenstandaard.nl/WS/MessageService/3.0", Order=0)]
        public Demo.tstRensaMessageService.MessageRequestType MessageRequest;
        
        public DeleteMessageRequest() {
        }
        
        public DeleteMessageRequest(Demo.tstRensaMessageService.CustomInfoType CustomInfo, Demo.tstRensaMessageService.MessageRequestType MessageRequest) {
            this.CustomInfo = CustomInfo;
            this.MessageRequest = MessageRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.ketenstandaard.nl/WS/MessageService/3.0", Order=0)]
        public Demo.tstRensaMessageService.MessageResponseType MessageResponse;
        
        public DeleteMessageResponse() {
        }
        
        public DeleteMessageResponse(Demo.tstRensaMessageService.MessageResponseType MessageResponse) {
            this.MessageResponse = MessageResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostMessageRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://www.ketenstandaard.nl/WS/MessageService/3.0")]
        public Demo.tstRensaMessageService.CustomInfoType CustomInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.ketenstandaard.nl/WS/MessageService/3.0", Order=0)]
        public Demo.tstRensaMessageService.MessageType Message;
        
        public PostMessageRequest() {
        }
        
        public PostMessageRequest(Demo.tstRensaMessageService.CustomInfoType CustomInfo, Demo.tstRensaMessageService.MessageType Message) {
            this.CustomInfo = CustomInfo;
            this.Message = Message;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMessageService30Channel : Demo.tstRensaMessageService.IMessageService30, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAvailableMessagesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAvailableMessagesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Demo.tstRensaMessageService.MessagePropertiesType[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Demo.tstRensaMessageService.MessagePropertiesType[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Demo.tstRensaMessageService.MessageRequestResponseType Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Demo.tstRensaMessageService.MessageRequestResponseType)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeleteMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public DeleteMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Demo.tstRensaMessageService.MessageResponseType Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Demo.tstRensaMessageService.MessageResponseType)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PostMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public PostMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Demo.tstRensaMessageService.MessageResponseType Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Demo.tstRensaMessageService.MessageResponseType)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MessageService30Client : System.ServiceModel.ClientBase<Demo.tstRensaMessageService.IMessageService30>, Demo.tstRensaMessageService.IMessageService30 {
        
        private BeginOperationDelegate onBeginGetAvailableMessagesDelegate;
        
        private EndOperationDelegate onEndGetAvailableMessagesDelegate;
        
        private System.Threading.SendOrPostCallback onGetAvailableMessagesCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetMessageDelegate;
        
        private EndOperationDelegate onEndGetMessageDelegate;
        
        private System.Threading.SendOrPostCallback onGetMessageCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeleteMessageDelegate;
        
        private EndOperationDelegate onEndDeleteMessageDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteMessageCompletedDelegate;
        
        private BeginOperationDelegate onBeginPostMessageDelegate;
        
        private EndOperationDelegate onEndPostMessageDelegate;
        
        private System.Threading.SendOrPostCallback onPostMessageCompletedDelegate;
        
        public MessageService30Client() {
        }
        
        public MessageService30Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MessageService30Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageService30Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageService30Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetAvailableMessagesCompletedEventArgs> GetAvailableMessagesCompleted;
        
        public event System.EventHandler<GetMessageCompletedEventArgs> GetMessageCompleted;
        
        public event System.EventHandler<DeleteMessageCompletedEventArgs> DeleteMessageCompleted;
        
        public event System.EventHandler<PostMessageCompletedEventArgs> PostMessageCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.tstRensaMessageService.GetAvailableMessagesResponse Demo.tstRensaMessageService.IMessageService30.GetAvailableMessages(Demo.tstRensaMessageService.GetAvailableMessagesRequest request) {
            return base.Channel.GetAvailableMessages(request);
        }
        
        public Demo.tstRensaMessageService.MessagePropertiesType[] GetAvailableMessages(Demo.tstRensaMessageService.CustomInfoType CustomInfo, Demo.tstRensaMessageService.AvailableMessagesRequestType AvailableMessagesRequest) {
            Demo.tstRensaMessageService.GetAvailableMessagesRequest inValue = new Demo.tstRensaMessageService.GetAvailableMessagesRequest();
            inValue.CustomInfo = CustomInfo;
            inValue.AvailableMessagesRequest = AvailableMessagesRequest;
            Demo.tstRensaMessageService.GetAvailableMessagesResponse retVal = ((Demo.tstRensaMessageService.IMessageService30)(this)).GetAvailableMessages(inValue);
            return retVal.AvailableMessagesResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Demo.tstRensaMessageService.IMessageService30.BeginGetAvailableMessages(Demo.tstRensaMessageService.GetAvailableMessagesRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAvailableMessages(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetAvailableMessages(Demo.tstRensaMessageService.CustomInfoType CustomInfo, Demo.tstRensaMessageService.AvailableMessagesRequestType AvailableMessagesRequest, System.AsyncCallback callback, object asyncState) {
            Demo.tstRensaMessageService.GetAvailableMessagesRequest inValue = new Demo.tstRensaMessageService.GetAvailableMessagesRequest();
            inValue.CustomInfo = CustomInfo;
            inValue.AvailableMessagesRequest = AvailableMessagesRequest;
            return ((Demo.tstRensaMessageService.IMessageService30)(this)).BeginGetAvailableMessages(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.tstRensaMessageService.GetAvailableMessagesResponse Demo.tstRensaMessageService.IMessageService30.EndGetAvailableMessages(System.IAsyncResult result) {
            return base.Channel.EndGetAvailableMessages(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Demo.tstRensaMessageService.MessagePropertiesType[] EndGetAvailableMessages(System.IAsyncResult result) {
            Demo.tstRensaMessageService.GetAvailableMessagesResponse retVal = ((Demo.tstRensaMessageService.IMessageService30)(this)).EndGetAvailableMessages(result);
            return retVal.AvailableMessagesResponse;
        }
        
        private System.IAsyncResult OnBeginGetAvailableMessages(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Demo.tstRensaMessageService.CustomInfoType CustomInfo = ((Demo.tstRensaMessageService.CustomInfoType)(inValues[0]));
            Demo.tstRensaMessageService.AvailableMessagesRequestType AvailableMessagesRequest = ((Demo.tstRensaMessageService.AvailableMessagesRequestType)(inValues[1]));
            return this.BeginGetAvailableMessages(CustomInfo, AvailableMessagesRequest, callback, asyncState);
        }
        
        private object[] OnEndGetAvailableMessages(System.IAsyncResult result) {
            Demo.tstRensaMessageService.MessagePropertiesType[] retVal = this.EndGetAvailableMessages(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAvailableMessagesCompleted(object state) {
            if ((this.GetAvailableMessagesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAvailableMessagesCompleted(this, new GetAvailableMessagesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAvailableMessagesAsync(Demo.tstRensaMessageService.CustomInfoType CustomInfo, Demo.tstRensaMessageService.AvailableMessagesRequestType AvailableMessagesRequest) {
            this.GetAvailableMessagesAsync(CustomInfo, AvailableMessagesRequest, null);
        }
        
        public void GetAvailableMessagesAsync(Demo.tstRensaMessageService.CustomInfoType CustomInfo, Demo.tstRensaMessageService.AvailableMessagesRequestType AvailableMessagesRequest, object userState) {
            if ((this.onBeginGetAvailableMessagesDelegate == null)) {
                this.onBeginGetAvailableMessagesDelegate = new BeginOperationDelegate(this.OnBeginGetAvailableMessages);
            }
            if ((this.onEndGetAvailableMessagesDelegate == null)) {
                this.onEndGetAvailableMessagesDelegate = new EndOperationDelegate(this.OnEndGetAvailableMessages);
            }
            if ((this.onGetAvailableMessagesCompletedDelegate == null)) {
                this.onGetAvailableMessagesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAvailableMessagesCompleted);
            }
            base.InvokeAsync(this.onBeginGetAvailableMessagesDelegate, new object[] {
                        CustomInfo,
                        AvailableMessagesRequest}, this.onEndGetAvailableMessagesDelegate, this.onGetAvailableMessagesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.tstRensaMessageService.GetMessageResponse Demo.tstRensaMessageService.IMessageService30.GetMessage(Demo.tstRensaMessageService.GetMessageRequest request) {
            return base.Channel.GetMessage(request);
        }
        
        public Demo.tstRensaMessageService.MessageRequestResponseType PostMessage(Demo.tstRensaMessageService.CustomInfoType CustomInfo, Demo.tstRensaMessageService.MessageRequestType MessageRequest) {
            Demo.tstRensaMessageService.GetMessageRequest inValue = new Demo.tstRensaMessageService.GetMessageRequest();
            inValue.CustomInfo = CustomInfo;
            inValue.MessageRequest = MessageRequest;
            Demo.tstRensaMessageService.GetMessageResponse retVal = ((Demo.tstRensaMessageService.IMessageService30)(this)).GetMessage(inValue);
            return retVal.MessageRequestResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Demo.tstRensaMessageService.IMessageService30.BeginGetMessage(Demo.tstRensaMessageService.GetMessageRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetMessage(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetMessage(Demo.tstRensaMessageService.CustomInfoType CustomInfo, Demo.tstRensaMessageService.MessageRequestType MessageRequest, System.AsyncCallback callback, object asyncState) {
            Demo.tstRensaMessageService.GetMessageRequest inValue = new Demo.tstRensaMessageService.GetMessageRequest();
            inValue.CustomInfo = CustomInfo;
            inValue.MessageRequest = MessageRequest;
            return ((Demo.tstRensaMessageService.IMessageService30)(this)).BeginGetMessage(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.tstRensaMessageService.GetMessageResponse Demo.tstRensaMessageService.IMessageService30.EndGetMessage(System.IAsyncResult result) {
            return base.Channel.EndGetMessage(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Demo.tstRensaMessageService.MessageRequestResponseType EndGetMessage(System.IAsyncResult result) {
            Demo.tstRensaMessageService.GetMessageResponse retVal = ((Demo.tstRensaMessageService.IMessageService30)(this)).EndGetMessage(result);
            return retVal.MessageRequestResponse;
        }
        
        private System.IAsyncResult OnBeginGetMessage(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Demo.tstRensaMessageService.CustomInfoType CustomInfo = ((Demo.tstRensaMessageService.CustomInfoType)(inValues[0]));
            Demo.tstRensaMessageService.MessageRequestType MessageRequest = ((Demo.tstRensaMessageService.MessageRequestType)(inValues[1]));
            return this.BeginGetMessage(CustomInfo, MessageRequest, callback, asyncState);
        }
        
        private object[] OnEndGetMessage(System.IAsyncResult result) {
            Demo.tstRensaMessageService.MessageRequestResponseType retVal = this.EndGetMessage(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetMessageCompleted(object state) {
            if ((this.GetMessageCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetMessageCompleted(this, new GetMessageCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetMessageAsync(Demo.tstRensaMessageService.CustomInfoType CustomInfo, Demo.tstRensaMessageService.MessageRequestType MessageRequest) {
            this.GetMessageAsync(CustomInfo, MessageRequest, null);
        }
        
        public void GetMessageAsync(Demo.tstRensaMessageService.CustomInfoType CustomInfo, Demo.tstRensaMessageService.MessageRequestType MessageRequest, object userState) {
            if ((this.onBeginGetMessageDelegate == null)) {
                this.onBeginGetMessageDelegate = new BeginOperationDelegate(this.OnBeginGetMessage);
            }
            if ((this.onEndGetMessageDelegate == null)) {
                this.onEndGetMessageDelegate = new EndOperationDelegate(this.OnEndGetMessage);
            }
            if ((this.onGetMessageCompletedDelegate == null)) {
                this.onGetMessageCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetMessageCompleted);
            }
            base.InvokeAsync(this.onBeginGetMessageDelegate, new object[] {
                        CustomInfo,
                        MessageRequest}, this.onEndGetMessageDelegate, this.onGetMessageCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.tstRensaMessageService.DeleteMessageResponse Demo.tstRensaMessageService.IMessageService30.DeleteMessage(Demo.tstRensaMessageService.DeleteMessageRequest request) {
            return base.Channel.DeleteMessage(request);
        }
        
        public Demo.tstRensaMessageService.MessageResponseType DeleteMessage(Demo.tstRensaMessageService.CustomInfoType CustomInfo, Demo.tstRensaMessageService.MessageRequestType MessageRequest) {
            Demo.tstRensaMessageService.DeleteMessageRequest inValue = new Demo.tstRensaMessageService.DeleteMessageRequest();
            inValue.CustomInfo = CustomInfo;
            inValue.MessageRequest = MessageRequest;
            Demo.tstRensaMessageService.DeleteMessageResponse retVal = ((Demo.tstRensaMessageService.IMessageService30)(this)).DeleteMessage(inValue);
            return retVal.MessageResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Demo.tstRensaMessageService.IMessageService30.BeginDeleteMessage(Demo.tstRensaMessageService.DeleteMessageRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDeleteMessage(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginDeleteMessage(Demo.tstRensaMessageService.CustomInfoType CustomInfo, Demo.tstRensaMessageService.MessageRequestType MessageRequest, System.AsyncCallback callback, object asyncState) {
            Demo.tstRensaMessageService.DeleteMessageRequest inValue = new Demo.tstRensaMessageService.DeleteMessageRequest();
            inValue.CustomInfo = CustomInfo;
            inValue.MessageRequest = MessageRequest;
            return ((Demo.tstRensaMessageService.IMessageService30)(this)).BeginDeleteMessage(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.tstRensaMessageService.DeleteMessageResponse Demo.tstRensaMessageService.IMessageService30.EndDeleteMessage(System.IAsyncResult result) {
            return base.Channel.EndDeleteMessage(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Demo.tstRensaMessageService.MessageResponseType EndDeleteMessage(System.IAsyncResult result) {
            Demo.tstRensaMessageService.DeleteMessageResponse retVal = ((Demo.tstRensaMessageService.IMessageService30)(this)).EndDeleteMessage(result);
            return retVal.MessageResponse;
        }
        
        private System.IAsyncResult OnBeginDeleteMessage(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Demo.tstRensaMessageService.CustomInfoType CustomInfo = ((Demo.tstRensaMessageService.CustomInfoType)(inValues[0]));
            Demo.tstRensaMessageService.MessageRequestType MessageRequest = ((Demo.tstRensaMessageService.MessageRequestType)(inValues[1]));
            return this.BeginDeleteMessage(CustomInfo, MessageRequest, callback, asyncState);
        }
        
        private object[] OnEndDeleteMessage(System.IAsyncResult result) {
            Demo.tstRensaMessageService.MessageResponseType retVal = this.EndDeleteMessage(result);
            return new object[] {
                    retVal};
        }
        
        private void OnDeleteMessageCompleted(object state) {
            if ((this.DeleteMessageCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteMessageCompleted(this, new DeleteMessageCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteMessageAsync(Demo.tstRensaMessageService.CustomInfoType CustomInfo, Demo.tstRensaMessageService.MessageRequestType MessageRequest) {
            this.DeleteMessageAsync(CustomInfo, MessageRequest, null);
        }
        
        public void DeleteMessageAsync(Demo.tstRensaMessageService.CustomInfoType CustomInfo, Demo.tstRensaMessageService.MessageRequestType MessageRequest, object userState) {
            if ((this.onBeginDeleteMessageDelegate == null)) {
                this.onBeginDeleteMessageDelegate = new BeginOperationDelegate(this.OnBeginDeleteMessage);
            }
            if ((this.onEndDeleteMessageDelegate == null)) {
                this.onEndDeleteMessageDelegate = new EndOperationDelegate(this.OnEndDeleteMessage);
            }
            if ((this.onDeleteMessageCompletedDelegate == null)) {
                this.onDeleteMessageCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteMessageCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteMessageDelegate, new object[] {
                        CustomInfo,
                        MessageRequest}, this.onEndDeleteMessageDelegate, this.onDeleteMessageCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.tstRensaMessageService.DeleteMessageResponse Demo.tstRensaMessageService.IMessageService30.PostMessage(Demo.tstRensaMessageService.PostMessageRequest request) {
            return base.Channel.PostMessage(request);
        }
        
        public Demo.tstRensaMessageService.MessageResponseType PostMessage(Demo.tstRensaMessageService.CustomInfoType CustomInfo, Demo.tstRensaMessageService.MessageType Message) {
            Demo.tstRensaMessageService.PostMessageRequest inValue = new Demo.tstRensaMessageService.PostMessageRequest();
            inValue.CustomInfo = CustomInfo;
            inValue.Message = Message;
            Demo.tstRensaMessageService.DeleteMessageResponse retVal = ((Demo.tstRensaMessageService.IMessageService30)(this)).PostMessage(inValue);
            return retVal.MessageResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Demo.tstRensaMessageService.IMessageService30.BeginPostMessage(Demo.tstRensaMessageService.PostMessageRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginPostMessage(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginPostMessage(Demo.tstRensaMessageService.CustomInfoType CustomInfo, Demo.tstRensaMessageService.MessageType Message, System.AsyncCallback callback, object asyncState) {
            Demo.tstRensaMessageService.PostMessageRequest inValue = new Demo.tstRensaMessageService.PostMessageRequest();
            inValue.CustomInfo = CustomInfo;
            inValue.Message = Message;
            return ((Demo.tstRensaMessageService.IMessageService30)(this)).BeginPostMessage(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.tstRensaMessageService.DeleteMessageResponse Demo.tstRensaMessageService.IMessageService30.EndPostMessage(System.IAsyncResult result) {
            return base.Channel.EndPostMessage(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Demo.tstRensaMessageService.MessageResponseType EndPostMessage(System.IAsyncResult result) {
            Demo.tstRensaMessageService.DeleteMessageResponse retVal = ((Demo.tstRensaMessageService.IMessageService30)(this)).EndPostMessage(result);
            return retVal.MessageResponse;
        }
        
        private System.IAsyncResult OnBeginPostMessage(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Demo.tstRensaMessageService.CustomInfoType CustomInfo = ((Demo.tstRensaMessageService.CustomInfoType)(inValues[0]));
            Demo.tstRensaMessageService.MessageType Message = ((Demo.tstRensaMessageService.MessageType)(inValues[1]));
            return this.BeginPostMessage(CustomInfo, Message, callback, asyncState);
        }
        
        private object[] OnEndPostMessage(System.IAsyncResult result) {
            Demo.tstRensaMessageService.MessageResponseType retVal = this.EndPostMessage(result);
            return new object[] {
                    retVal};
        }
        
        private void OnPostMessageCompleted(object state) {
            if ((this.PostMessageCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.PostMessageCompleted(this, new PostMessageCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void PostMessageAsync(Demo.tstRensaMessageService.CustomInfoType CustomInfo, Demo.tstRensaMessageService.MessageType Message) {
            this.PostMessageAsync(CustomInfo, Message, null);
        }
        
        public void PostMessageAsync(Demo.tstRensaMessageService.CustomInfoType CustomInfo, Demo.tstRensaMessageService.MessageType Message, object userState) {
            if ((this.onBeginPostMessageDelegate == null)) {
                this.onBeginPostMessageDelegate = new BeginOperationDelegate(this.OnBeginPostMessage);
            }
            if ((this.onEndPostMessageDelegate == null)) {
                this.onEndPostMessageDelegate = new EndOperationDelegate(this.OnEndPostMessage);
            }
            if ((this.onPostMessageCompletedDelegate == null)) {
                this.onPostMessageCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnPostMessageCompleted);
            }
            base.InvokeAsync(this.onBeginPostMessageDelegate, new object[] {
                        CustomInfo,
                        Message}, this.onEndPostMessageDelegate, this.onPostMessageCompletedDelegate, userState);
        }
    }
}
