//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.ClientGDBAttachment {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AttachmentViewOption", Namespace="http://Compano.com/Modules/GDB")]
    public enum AttachmentViewOption : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AllAttachments = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Attachment = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FilterElement", Namespace="http://Compano.com/Modules/GDB")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientGDBAttachment.AttachmentViewOption))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientGDBAttachment.FilterElement[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientGDBAttachment.ConditionTypeOption))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientGDBAttachment.AttachmentXmlField[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientGDBAttachment.AttachmentXmlField))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientGDBAttachment.AttachmentFilterField[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientGDBAttachment.AttachmentFilterField))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientGDBAttachment.ArrayOfString))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientGDBAttachment.Facet))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientGDBAttachment.FacetItem[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientGDBAttachment.FacetItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientGDBAttachment.Facet[]))]
    public partial class FilterElement : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Demo.ClientGDBAttachment.ConditionTypeOption ConditionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FieldNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object Value1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object Value2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Demo.ClientGDBAttachment.ConditionTypeOption ConditionType {
            get {
                return this.ConditionTypeField;
            }
            set {
                if ((this.ConditionTypeField.Equals(value) != true)) {
                    this.ConditionTypeField = value;
                    this.RaisePropertyChanged("ConditionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FieldName {
            get {
                return this.FieldNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldNameField, value) != true)) {
                    this.FieldNameField = value;
                    this.RaisePropertyChanged("FieldName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public object Value1 {
            get {
                return this.Value1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Value1Field, value) != true)) {
                    this.Value1Field = value;
                    this.RaisePropertyChanged("Value1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public object Value2 {
            get {
                return this.Value2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Value2Field, value) != true)) {
                    this.Value2Field = value;
                    this.RaisePropertyChanged("Value2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConditionTypeOption", Namespace="http://Compano.com/Modules/GDB")]
    public enum ConditionTypeOption : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Equals = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EqualsField = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GreaterThan = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GreaterThanField = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GreaterThanOrEquals = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GreaterThanOrEqualsField = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LesserThan = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LesserThanField = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LesserThanOrEquals = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LesserThanOrEqualsField = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Between = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Outside = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Contains = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotContains = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EqualsNoCase = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ItemInSet = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        StartsWith = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EndsWith = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InRange = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotNull = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Null = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HasChilds = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HasNoChilds = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InAudience = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Approximately = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ApproximatelyField = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InRangeField = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LastWeek = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LastMonth = 28,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NextWeek = 29,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NextMonth = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotEquals = 31,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotEqualsField = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ItemNotInSet = 33,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HasUnarchivedChilds = 34,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HasNoUnarchivedChilds = 35,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        All = 36,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AttachmentXmlField", Namespace="http://Compano.com/Modules/GDB")]
    public enum AttachmentXmlField : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ArchivedDateTime = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ArchivedDateTimeAsMonth = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ArchivedDateTimeAsQuarter = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ArchivedDateTimeAsWeek = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ArchivedDateTimeAsYear = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ConstantNow = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ConstantText = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ConstantToday = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Description = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Extension = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IsArchived = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LanguageCode = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ParentDescription = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ParentEntityDescription = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ParentKey = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Path = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SequenceNo = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Source = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Title = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Type = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UploadDateTime = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UploadDateTimeAsMonth = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UploadDateTimeAsQuarter = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UploadDateTimeAsWeek = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UploadDateTimeAsYear = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Version = 25,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AttachmentFilterField", Namespace="http://Compano.com/Modules/GDB")]
    public enum AttachmentFilterField : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ArchivedDateTime = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ArchivedDateTimeAsMonth = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ArchivedDateTimeAsQuarter = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ArchivedDateTimeAsWeek = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ArchivedDateTimeAsYear = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ConstantNow = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ConstantToday = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Extension = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IsArchived = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Language = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LanguageCode = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Parent = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ParentEntity = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ParentKey = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SequenceNo = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Source = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Title = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Type = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UploadDateTime = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UploadDateTimeAsMonth = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UploadDateTimeAsQuarter = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UploadDateTimeAsWeek = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UploadDateTimeAsYear = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Version = 23,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://Compano.com/Modules/GDB", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Facet", Namespace="http://Compano.com/Modules/GDB")]
    [System.SerializableAttribute()]
    public partial class Facet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        private bool IsSelectedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Demo.ClientGDBAttachment.FacetItem[] ItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Demo.ClientGDBAttachment.FacetItem SelectedItemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool IsSelected {
            get {
                return this.IsSelectedField;
            }
            set {
                if ((this.IsSelectedField.Equals(value) != true)) {
                    this.IsSelectedField = value;
                    this.RaisePropertyChanged("IsSelected");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Demo.ClientGDBAttachment.FacetItem[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Demo.ClientGDBAttachment.FacetItem SelectedItem {
            get {
                return this.SelectedItemField;
            }
            set {
                if ((object.ReferenceEquals(this.SelectedItemField, value) != true)) {
                    this.SelectedItemField = value;
                    this.RaisePropertyChanged("SelectedItem");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FacetItem", Namespace="http://Compano.com/Modules/GDB")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientGDBAttachment.AttachmentViewOption))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientGDBAttachment.FilterElement[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientGDBAttachment.FilterElement))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientGDBAttachment.ConditionTypeOption))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientGDBAttachment.AttachmentXmlField[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientGDBAttachment.AttachmentXmlField))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientGDBAttachment.AttachmentFilterField[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientGDBAttachment.AttachmentFilterField))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientGDBAttachment.ArrayOfString))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientGDBAttachment.Facet))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientGDBAttachment.FacetItem[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demo.ClientGDBAttachment.Facet[]))]
    public partial class FacetItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        private int RecordCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object KeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RecordCount {
            get {
                return this.RecordCountField;
            }
            set {
                if ((this.RecordCountField.Equals(value) != true)) {
                    this.RecordCountField = value;
                    this.RaisePropertyChanged("RecordCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Unit {
            get {
                return this.UnitField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitField, value) != true)) {
                    this.UnitField = value;
                    this.RaisePropertyChanged("Unit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public object Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Compano.com/Modules/GDB", ConfigurationName="ClientGDBAttachment.AttachmentServiceSoap")]
    public interface AttachmentServiceSoap {
        
        // CODEGEN: Generating message contract since element name sessionHandle from namespace http://Compano.com/Modules/GDB is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Compano.com/Modules/GDB/SetDefaultView", ReplyAction="*")]
        Demo.ClientGDBAttachment.SetDefaultViewResponse SetDefaultView(Demo.ClientGDBAttachment.SetDefaultViewRequest request);
        
        // CODEGEN: Generating message contract since element name sessionHandle from namespace http://Compano.com/Modules/GDB is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Compano.com/Modules/GDB/SelectAsJSON", ReplyAction="*")]
        Demo.ClientGDBAttachment.SelectAsJSONResponse SelectAsJSON(Demo.ClientGDBAttachment.SelectAsJSONRequest request);
        
        // CODEGEN: Generating message contract since element name sessionHandle from namespace http://Compano.com/Modules/GDB is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Compano.com/Modules/GDB/Select", ReplyAction="*")]
        Demo.ClientGDBAttachment.SelectResponse Select(Demo.ClientGDBAttachment.SelectRequest request);
        
        // CODEGEN: Generating message contract since element name sessionHandle from namespace http://Compano.com/Modules/GDB is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Compano.com/Modules/GDB/GetGridUrl", ReplyAction="*")]
        Demo.ClientGDBAttachment.GetGridUrlResponse GetGridUrl(Demo.ClientGDBAttachment.GetGridUrlRequest request);
        
        // CODEGEN: Generating message contract since element name sessionHandle from namespace http://Compano.com/Modules/GDB is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Compano.com/Modules/GDB/GetViewAsXml", ReplyAction="*")]
        Demo.ClientGDBAttachment.GetViewAsXmlResponse GetViewAsXml(Demo.ClientGDBAttachment.GetViewAsXmlRequest request);
        
        // CODEGEN: Generating message contract since element name sessionHandle from namespace http://Compano.com/Modules/GDB is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Compano.com/Modules/GDB/SetViewFilter", ReplyAction="*")]
        Demo.ClientGDBAttachment.SetViewFilterResponse SetViewFilter(Demo.ClientGDBAttachment.SetViewFilterRequest request);
        
        // CODEGEN: Generating message contract since element name sessionHandle from namespace http://Compano.com/Modules/GDB is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Compano.com/Modules/GDB/SetViewSortOrder", ReplyAction="*")]
        Demo.ClientGDBAttachment.SetViewSortOrderResponse SetViewSortOrder(Demo.ClientGDBAttachment.SetViewSortOrderRequest request);
        
        // CODEGEN: Generating message contract since element name sessionHandle from namespace http://Compano.com/Modules/GDB is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Compano.com/Modules/GDB/GetViewCount", ReplyAction="*")]
        Demo.ClientGDBAttachment.GetViewCountResponse GetViewCount(Demo.ClientGDBAttachment.GetViewCountRequest request);
        
        // CODEGEN: Generating message contract since element name sessionHandle from namespace http://Compano.com/Modules/GDB is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Compano.com/Modules/GDB/ResetViewFilter", ReplyAction="*")]
        Demo.ClientGDBAttachment.ResetViewFilterResponse ResetViewFilter(Demo.ClientGDBAttachment.ResetViewFilterRequest request);
        
        // CODEGEN: Generating message contract since element name sessionHandle from namespace http://Compano.com/Modules/GDB is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Compano.com/Modules/GDB/SetViewAdvancedFilter", ReplyAction="*")]
        Demo.ClientGDBAttachment.SetViewAdvancedFilterResponse SetViewAdvancedFilter(Demo.ClientGDBAttachment.SetViewAdvancedFilterRequest request);
        
        // CODEGEN: Generating message contract since element name sessionHandle from namespace http://Compano.com/Modules/GDB is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Compano.com/Modules/GDB/SetViewSearchText", ReplyAction="*")]
        Demo.ClientGDBAttachment.SetViewSearchTextResponse SetViewSearchText(Demo.ClientGDBAttachment.SetViewSearchTextRequest request);
        
        // CODEGEN: Generating message contract since element name sessionHandle from namespace http://Compano.com/Modules/GDB is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Compano.com/Modules/GDB/SetViewFacet", ReplyAction="*")]
        Demo.ClientGDBAttachment.SetViewFacetResponse SetViewFacet(Demo.ClientGDBAttachment.SetViewFacetRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetDefaultViewRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetDefaultView", Namespace="http://Compano.com/Modules/GDB", Order=0)]
        public Demo.ClientGDBAttachment.SetDefaultViewRequestBody Body;
        
        public SetDefaultViewRequest() {
        }
        
        public SetDefaultViewRequest(Demo.ClientGDBAttachment.SetDefaultViewRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/GDB")]
    public partial class SetDefaultViewRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionHandle;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public Demo.ClientGDBAttachment.AttachmentViewOption view;
        
        public SetDefaultViewRequestBody() {
        }
        
        public SetDefaultViewRequestBody(string sessionHandle, Demo.ClientGDBAttachment.AttachmentViewOption view) {
            this.sessionHandle = sessionHandle;
            this.view = view;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetDefaultViewResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetDefaultViewResponse", Namespace="http://Compano.com/Modules/GDB", Order=0)]
        public Demo.ClientGDBAttachment.SetDefaultViewResponseBody Body;
        
        public SetDefaultViewResponse() {
        }
        
        public SetDefaultViewResponse(Demo.ClientGDBAttachment.SetDefaultViewResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/GDB")]
    public partial class SetDefaultViewResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SetDefaultViewResult;
        
        public SetDefaultViewResponseBody() {
        }
        
        public SetDefaultViewResponseBody(string SetDefaultViewResult) {
            this.SetDefaultViewResult = SetDefaultViewResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAsJSONRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectAsJSON", Namespace="http://Compano.com/Modules/GDB", Order=0)]
        public Demo.ClientGDBAttachment.SelectAsJSONRequestBody Body;
        
        public SelectAsJSONRequest() {
        }
        
        public SelectAsJSONRequest(Demo.ClientGDBAttachment.SelectAsJSONRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/GDB")]
    public partial class SelectAsJSONRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionHandle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Demo.ClientGDBAttachment.FilterElement[] filterElements;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Demo.ClientGDBAttachment.AttachmentXmlField[] fields;
        
        public SelectAsJSONRequestBody() {
        }
        
        public SelectAsJSONRequestBody(string sessionHandle, Demo.ClientGDBAttachment.FilterElement[] filterElements, Demo.ClientGDBAttachment.AttachmentXmlField[] fields) {
            this.sessionHandle = sessionHandle;
            this.filterElements = filterElements;
            this.fields = fields;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAsJSONResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectAsJSONResponse", Namespace="http://Compano.com/Modules/GDB", Order=0)]
        public Demo.ClientGDBAttachment.SelectAsJSONResponseBody Body;
        
        public SelectAsJSONResponse() {
        }
        
        public SelectAsJSONResponse(Demo.ClientGDBAttachment.SelectAsJSONResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/GDB")]
    public partial class SelectAsJSONResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SelectAsJSONResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string json;
        
        public SelectAsJSONResponseBody() {
        }
        
        public SelectAsJSONResponseBody(string SelectAsJSONResult, string json) {
            this.SelectAsJSONResult = SelectAsJSONResult;
            this.json = json;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Select", Namespace="http://Compano.com/Modules/GDB", Order=0)]
        public Demo.ClientGDBAttachment.SelectRequestBody Body;
        
        public SelectRequest() {
        }
        
        public SelectRequest(Demo.ClientGDBAttachment.SelectRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/GDB")]
    public partial class SelectRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionHandle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Demo.ClientGDBAttachment.AttachmentFilterField[] filterFields;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Demo.ClientGDBAttachment.ArrayOfString filterValues;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string searchText;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public Demo.ClientGDBAttachment.AttachmentXmlField[] fields;
        
        public SelectRequestBody() {
        }
        
        public SelectRequestBody(string sessionHandle, Demo.ClientGDBAttachment.AttachmentFilterField[] filterFields, Demo.ClientGDBAttachment.ArrayOfString filterValues, string searchText, Demo.ClientGDBAttachment.AttachmentXmlField[] fields) {
            this.sessionHandle = sessionHandle;
            this.filterFields = filterFields;
            this.filterValues = filterValues;
            this.searchText = searchText;
            this.fields = fields;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectResponse", Namespace="http://Compano.com/Modules/GDB", Order=0)]
        public Demo.ClientGDBAttachment.SelectResponseBody Body;
        
        public SelectResponse() {
        }
        
        public SelectResponse(Demo.ClientGDBAttachment.SelectResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/GDB")]
    public partial class SelectResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SelectResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string xml;
        
        public SelectResponseBody() {
        }
        
        public SelectResponseBody(string SelectResult, string xml) {
            this.SelectResult = SelectResult;
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGridUrlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGridUrl", Namespace="http://Compano.com/Modules/GDB", Order=0)]
        public Demo.ClientGDBAttachment.GetGridUrlRequestBody Body;
        
        public GetGridUrlRequest() {
        }
        
        public GetGridUrlRequest(Demo.ClientGDBAttachment.GetGridUrlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/GDB")]
    public partial class GetGridUrlRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionHandle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Demo.ClientGDBAttachment.AttachmentFilterField[] filterFields;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Demo.ClientGDBAttachment.ArrayOfString filterValues;
        
        public GetGridUrlRequestBody() {
        }
        
        public GetGridUrlRequestBody(string sessionHandle, Demo.ClientGDBAttachment.AttachmentFilterField[] filterFields, Demo.ClientGDBAttachment.ArrayOfString filterValues) {
            this.sessionHandle = sessionHandle;
            this.filterFields = filterFields;
            this.filterValues = filterValues;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGridUrlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGridUrlResponse", Namespace="http://Compano.com/Modules/GDB", Order=0)]
        public Demo.ClientGDBAttachment.GetGridUrlResponseBody Body;
        
        public GetGridUrlResponse() {
        }
        
        public GetGridUrlResponse(Demo.ClientGDBAttachment.GetGridUrlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/GDB")]
    public partial class GetGridUrlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetGridUrlResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string url;
        
        public GetGridUrlResponseBody() {
        }
        
        public GetGridUrlResponseBody(string GetGridUrlResult, string url) {
            this.GetGridUrlResult = GetGridUrlResult;
            this.url = url;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetViewAsXmlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetViewAsXml", Namespace="http://Compano.com/Modules/GDB", Order=0)]
        public Demo.ClientGDBAttachment.GetViewAsXmlRequestBody Body;
        
        public GetViewAsXmlRequest() {
        }
        
        public GetViewAsXmlRequest(Demo.ClientGDBAttachment.GetViewAsXmlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/GDB")]
    public partial class GetViewAsXmlRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionHandle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Demo.ClientGDBAttachment.AttachmentXmlField[] fields;
        
        public GetViewAsXmlRequestBody() {
        }
        
        public GetViewAsXmlRequestBody(string sessionHandle, Demo.ClientGDBAttachment.AttachmentXmlField[] fields) {
            this.sessionHandle = sessionHandle;
            this.fields = fields;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetViewAsXmlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetViewAsXmlResponse", Namespace="http://Compano.com/Modules/GDB", Order=0)]
        public Demo.ClientGDBAttachment.GetViewAsXmlResponseBody Body;
        
        public GetViewAsXmlResponse() {
        }
        
        public GetViewAsXmlResponse(Demo.ClientGDBAttachment.GetViewAsXmlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/GDB")]
    public partial class GetViewAsXmlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetViewAsXmlResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string xml;
        
        public GetViewAsXmlResponseBody() {
        }
        
        public GetViewAsXmlResponseBody(string GetViewAsXmlResult, string xml) {
            this.GetViewAsXmlResult = GetViewAsXmlResult;
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetViewFilterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetViewFilter", Namespace="http://Compano.com/Modules/GDB", Order=0)]
        public Demo.ClientGDBAttachment.SetViewFilterRequestBody Body;
        
        public SetViewFilterRequest() {
        }
        
        public SetViewFilterRequest(Demo.ClientGDBAttachment.SetViewFilterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/GDB")]
    public partial class SetViewFilterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionHandle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Demo.ClientGDBAttachment.AttachmentFilterField[] filterFields;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Demo.ClientGDBAttachment.ArrayOfString filterValues;
        
        public SetViewFilterRequestBody() {
        }
        
        public SetViewFilterRequestBody(string sessionHandle, Demo.ClientGDBAttachment.AttachmentFilterField[] filterFields, Demo.ClientGDBAttachment.ArrayOfString filterValues) {
            this.sessionHandle = sessionHandle;
            this.filterFields = filterFields;
            this.filterValues = filterValues;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetViewFilterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetViewFilterResponse", Namespace="http://Compano.com/Modules/GDB", Order=0)]
        public Demo.ClientGDBAttachment.SetViewFilterResponseBody Body;
        
        public SetViewFilterResponse() {
        }
        
        public SetViewFilterResponse(Demo.ClientGDBAttachment.SetViewFilterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/GDB")]
    public partial class SetViewFilterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SetViewFilterResult;
        
        public SetViewFilterResponseBody() {
        }
        
        public SetViewFilterResponseBody(string SetViewFilterResult) {
            this.SetViewFilterResult = SetViewFilterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetViewSortOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetViewSortOrder", Namespace="http://Compano.com/Modules/GDB", Order=0)]
        public Demo.ClientGDBAttachment.SetViewSortOrderRequestBody Body;
        
        public SetViewSortOrderRequest() {
        }
        
        public SetViewSortOrderRequest(Demo.ClientGDBAttachment.SetViewSortOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/GDB")]
    public partial class SetViewSortOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionHandle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sortExpression;
        
        public SetViewSortOrderRequestBody() {
        }
        
        public SetViewSortOrderRequestBody(string sessionHandle, string sortExpression) {
            this.sessionHandle = sessionHandle;
            this.sortExpression = sortExpression;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetViewSortOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetViewSortOrderResponse", Namespace="http://Compano.com/Modules/GDB", Order=0)]
        public Demo.ClientGDBAttachment.SetViewSortOrderResponseBody Body;
        
        public SetViewSortOrderResponse() {
        }
        
        public SetViewSortOrderResponse(Demo.ClientGDBAttachment.SetViewSortOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/GDB")]
    public partial class SetViewSortOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SetViewSortOrderResult;
        
        public SetViewSortOrderResponseBody() {
        }
        
        public SetViewSortOrderResponseBody(string SetViewSortOrderResult) {
            this.SetViewSortOrderResult = SetViewSortOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetViewCountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetViewCount", Namespace="http://Compano.com/Modules/GDB", Order=0)]
        public Demo.ClientGDBAttachment.GetViewCountRequestBody Body;
        
        public GetViewCountRequest() {
        }
        
        public GetViewCountRequest(Demo.ClientGDBAttachment.GetViewCountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/GDB")]
    public partial class GetViewCountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionHandle;
        
        public GetViewCountRequestBody() {
        }
        
        public GetViewCountRequestBody(string sessionHandle) {
            this.sessionHandle = sessionHandle;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetViewCountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetViewCountResponse", Namespace="http://Compano.com/Modules/GDB", Order=0)]
        public Demo.ClientGDBAttachment.GetViewCountResponseBody Body;
        
        public GetViewCountResponse() {
        }
        
        public GetViewCountResponse(Demo.ClientGDBAttachment.GetViewCountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/GDB")]
    public partial class GetViewCountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetViewCountResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int recordCount;
        
        public GetViewCountResponseBody() {
        }
        
        public GetViewCountResponseBody(string GetViewCountResult, int recordCount) {
            this.GetViewCountResult = GetViewCountResult;
            this.recordCount = recordCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResetViewFilterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResetViewFilter", Namespace="http://Compano.com/Modules/GDB", Order=0)]
        public Demo.ClientGDBAttachment.ResetViewFilterRequestBody Body;
        
        public ResetViewFilterRequest() {
        }
        
        public ResetViewFilterRequest(Demo.ClientGDBAttachment.ResetViewFilterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/GDB")]
    public partial class ResetViewFilterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionHandle;
        
        public ResetViewFilterRequestBody() {
        }
        
        public ResetViewFilterRequestBody(string sessionHandle) {
            this.sessionHandle = sessionHandle;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResetViewFilterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResetViewFilterResponse", Namespace="http://Compano.com/Modules/GDB", Order=0)]
        public Demo.ClientGDBAttachment.ResetViewFilterResponseBody Body;
        
        public ResetViewFilterResponse() {
        }
        
        public ResetViewFilterResponse(Demo.ClientGDBAttachment.ResetViewFilterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/GDB")]
    public partial class ResetViewFilterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ResetViewFilterResult;
        
        public ResetViewFilterResponseBody() {
        }
        
        public ResetViewFilterResponseBody(string ResetViewFilterResult) {
            this.ResetViewFilterResult = ResetViewFilterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetViewAdvancedFilterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetViewAdvancedFilter", Namespace="http://Compano.com/Modules/GDB", Order=0)]
        public Demo.ClientGDBAttachment.SetViewAdvancedFilterRequestBody Body;
        
        public SetViewAdvancedFilterRequest() {
        }
        
        public SetViewAdvancedFilterRequest(Demo.ClientGDBAttachment.SetViewAdvancedFilterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/GDB")]
    public partial class SetViewAdvancedFilterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionHandle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Demo.ClientGDBAttachment.FilterElement[] filterElements;
        
        public SetViewAdvancedFilterRequestBody() {
        }
        
        public SetViewAdvancedFilterRequestBody(string sessionHandle, Demo.ClientGDBAttachment.FilterElement[] filterElements) {
            this.sessionHandle = sessionHandle;
            this.filterElements = filterElements;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetViewAdvancedFilterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetViewAdvancedFilterResponse", Namespace="http://Compano.com/Modules/GDB", Order=0)]
        public Demo.ClientGDBAttachment.SetViewAdvancedFilterResponseBody Body;
        
        public SetViewAdvancedFilterResponse() {
        }
        
        public SetViewAdvancedFilterResponse(Demo.ClientGDBAttachment.SetViewAdvancedFilterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/GDB")]
    public partial class SetViewAdvancedFilterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SetViewAdvancedFilterResult;
        
        public SetViewAdvancedFilterResponseBody() {
        }
        
        public SetViewAdvancedFilterResponseBody(string SetViewAdvancedFilterResult) {
            this.SetViewAdvancedFilterResult = SetViewAdvancedFilterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetViewSearchTextRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetViewSearchText", Namespace="http://Compano.com/Modules/GDB", Order=0)]
        public Demo.ClientGDBAttachment.SetViewSearchTextRequestBody Body;
        
        public SetViewSearchTextRequest() {
        }
        
        public SetViewSearchTextRequest(Demo.ClientGDBAttachment.SetViewSearchTextRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/GDB")]
    public partial class SetViewSearchTextRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionHandle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string searchText;
        
        public SetViewSearchTextRequestBody() {
        }
        
        public SetViewSearchTextRequestBody(string sessionHandle, string searchText) {
            this.sessionHandle = sessionHandle;
            this.searchText = searchText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetViewSearchTextResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetViewSearchTextResponse", Namespace="http://Compano.com/Modules/GDB", Order=0)]
        public Demo.ClientGDBAttachment.SetViewSearchTextResponseBody Body;
        
        public SetViewSearchTextResponse() {
        }
        
        public SetViewSearchTextResponse(Demo.ClientGDBAttachment.SetViewSearchTextResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/GDB")]
    public partial class SetViewSearchTextResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SetViewSearchTextResult;
        
        public SetViewSearchTextResponseBody() {
        }
        
        public SetViewSearchTextResponseBody(string SetViewSearchTextResult) {
            this.SetViewSearchTextResult = SetViewSearchTextResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetViewFacetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetViewFacet", Namespace="http://Compano.com/Modules/GDB", Order=0)]
        public Demo.ClientGDBAttachment.SetViewFacetRequestBody Body;
        
        public SetViewFacetRequest() {
        }
        
        public SetViewFacetRequest(Demo.ClientGDBAttachment.SetViewFacetRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/GDB")]
    public partial class SetViewFacetRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionHandle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string selectedFacetItem;
        
        public SetViewFacetRequestBody() {
        }
        
        public SetViewFacetRequestBody(string sessionHandle, string selectedFacetItem) {
            this.sessionHandle = sessionHandle;
            this.selectedFacetItem = selectedFacetItem;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetViewFacetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetViewFacetResponse", Namespace="http://Compano.com/Modules/GDB", Order=0)]
        public Demo.ClientGDBAttachment.SetViewFacetResponseBody Body;
        
        public SetViewFacetResponse() {
        }
        
        public SetViewFacetResponse(Demo.ClientGDBAttachment.SetViewFacetResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Compano.com/Modules/GDB")]
    public partial class SetViewFacetResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SetViewFacetResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Demo.ClientGDBAttachment.Facet[] facets;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int recordCount;
        
        public SetViewFacetResponseBody() {
        }
        
        public SetViewFacetResponseBody(string SetViewFacetResult, Demo.ClientGDBAttachment.Facet[] facets, int recordCount) {
            this.SetViewFacetResult = SetViewFacetResult;
            this.facets = facets;
            this.recordCount = recordCount;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AttachmentServiceSoapChannel : Demo.ClientGDBAttachment.AttachmentServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AttachmentServiceSoapClient : System.ServiceModel.ClientBase<Demo.ClientGDBAttachment.AttachmentServiceSoap>, Demo.ClientGDBAttachment.AttachmentServiceSoap {
        
        public AttachmentServiceSoapClient() {
        }
        
        public AttachmentServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AttachmentServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AttachmentServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AttachmentServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.ClientGDBAttachment.SetDefaultViewResponse Demo.ClientGDBAttachment.AttachmentServiceSoap.SetDefaultView(Demo.ClientGDBAttachment.SetDefaultViewRequest request) {
            return base.Channel.SetDefaultView(request);
        }
        
        public string SetDefaultView(string sessionHandle, Demo.ClientGDBAttachment.AttachmentViewOption view) {
            Demo.ClientGDBAttachment.SetDefaultViewRequest inValue = new Demo.ClientGDBAttachment.SetDefaultViewRequest();
            inValue.Body = new Demo.ClientGDBAttachment.SetDefaultViewRequestBody();
            inValue.Body.sessionHandle = sessionHandle;
            inValue.Body.view = view;
            Demo.ClientGDBAttachment.SetDefaultViewResponse retVal = ((Demo.ClientGDBAttachment.AttachmentServiceSoap)(this)).SetDefaultView(inValue);
            return retVal.Body.SetDefaultViewResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.ClientGDBAttachment.SelectAsJSONResponse Demo.ClientGDBAttachment.AttachmentServiceSoap.SelectAsJSON(Demo.ClientGDBAttachment.SelectAsJSONRequest request) {
            return base.Channel.SelectAsJSON(request);
        }
        
        public string SelectAsJSON(string sessionHandle, Demo.ClientGDBAttachment.FilterElement[] filterElements, Demo.ClientGDBAttachment.AttachmentXmlField[] fields, out string json) {
            Demo.ClientGDBAttachment.SelectAsJSONRequest inValue = new Demo.ClientGDBAttachment.SelectAsJSONRequest();
            inValue.Body = new Demo.ClientGDBAttachment.SelectAsJSONRequestBody();
            inValue.Body.sessionHandle = sessionHandle;
            inValue.Body.filterElements = filterElements;
            inValue.Body.fields = fields;
            Demo.ClientGDBAttachment.SelectAsJSONResponse retVal = ((Demo.ClientGDBAttachment.AttachmentServiceSoap)(this)).SelectAsJSON(inValue);
            json = retVal.Body.json;
            return retVal.Body.SelectAsJSONResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.ClientGDBAttachment.SelectResponse Demo.ClientGDBAttachment.AttachmentServiceSoap.Select(Demo.ClientGDBAttachment.SelectRequest request) {
            return base.Channel.Select(request);
        }
        
        public string Select(string sessionHandle, Demo.ClientGDBAttachment.AttachmentFilterField[] filterFields, Demo.ClientGDBAttachment.ArrayOfString filterValues, string searchText, Demo.ClientGDBAttachment.AttachmentXmlField[] fields, out string xml) {
            Demo.ClientGDBAttachment.SelectRequest inValue = new Demo.ClientGDBAttachment.SelectRequest();
            inValue.Body = new Demo.ClientGDBAttachment.SelectRequestBody();
            inValue.Body.sessionHandle = sessionHandle;
            inValue.Body.filterFields = filterFields;
            inValue.Body.filterValues = filterValues;
            inValue.Body.searchText = searchText;
            inValue.Body.fields = fields;
            Demo.ClientGDBAttachment.SelectResponse retVal = ((Demo.ClientGDBAttachment.AttachmentServiceSoap)(this)).Select(inValue);
            xml = retVal.Body.xml;
            return retVal.Body.SelectResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.ClientGDBAttachment.GetGridUrlResponse Demo.ClientGDBAttachment.AttachmentServiceSoap.GetGridUrl(Demo.ClientGDBAttachment.GetGridUrlRequest request) {
            return base.Channel.GetGridUrl(request);
        }
        
        public string GetGridUrl(string sessionHandle, Demo.ClientGDBAttachment.AttachmentFilterField[] filterFields, Demo.ClientGDBAttachment.ArrayOfString filterValues, out string url) {
            Demo.ClientGDBAttachment.GetGridUrlRequest inValue = new Demo.ClientGDBAttachment.GetGridUrlRequest();
            inValue.Body = new Demo.ClientGDBAttachment.GetGridUrlRequestBody();
            inValue.Body.sessionHandle = sessionHandle;
            inValue.Body.filterFields = filterFields;
            inValue.Body.filterValues = filterValues;
            Demo.ClientGDBAttachment.GetGridUrlResponse retVal = ((Demo.ClientGDBAttachment.AttachmentServiceSoap)(this)).GetGridUrl(inValue);
            url = retVal.Body.url;
            return retVal.Body.GetGridUrlResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.ClientGDBAttachment.GetViewAsXmlResponse Demo.ClientGDBAttachment.AttachmentServiceSoap.GetViewAsXml(Demo.ClientGDBAttachment.GetViewAsXmlRequest request) {
            return base.Channel.GetViewAsXml(request);
        }
        
        public string GetViewAsXml(string sessionHandle, Demo.ClientGDBAttachment.AttachmentXmlField[] fields, out string xml) {
            Demo.ClientGDBAttachment.GetViewAsXmlRequest inValue = new Demo.ClientGDBAttachment.GetViewAsXmlRequest();
            inValue.Body = new Demo.ClientGDBAttachment.GetViewAsXmlRequestBody();
            inValue.Body.sessionHandle = sessionHandle;
            inValue.Body.fields = fields;
            Demo.ClientGDBAttachment.GetViewAsXmlResponse retVal = ((Demo.ClientGDBAttachment.AttachmentServiceSoap)(this)).GetViewAsXml(inValue);
            xml = retVal.Body.xml;
            return retVal.Body.GetViewAsXmlResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.ClientGDBAttachment.SetViewFilterResponse Demo.ClientGDBAttachment.AttachmentServiceSoap.SetViewFilter(Demo.ClientGDBAttachment.SetViewFilterRequest request) {
            return base.Channel.SetViewFilter(request);
        }
        
        public string SetViewFilter(string sessionHandle, Demo.ClientGDBAttachment.AttachmentFilterField[] filterFields, Demo.ClientGDBAttachment.ArrayOfString filterValues) {
            Demo.ClientGDBAttachment.SetViewFilterRequest inValue = new Demo.ClientGDBAttachment.SetViewFilterRequest();
            inValue.Body = new Demo.ClientGDBAttachment.SetViewFilterRequestBody();
            inValue.Body.sessionHandle = sessionHandle;
            inValue.Body.filterFields = filterFields;
            inValue.Body.filterValues = filterValues;
            Demo.ClientGDBAttachment.SetViewFilterResponse retVal = ((Demo.ClientGDBAttachment.AttachmentServiceSoap)(this)).SetViewFilter(inValue);
            return retVal.Body.SetViewFilterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.ClientGDBAttachment.SetViewSortOrderResponse Demo.ClientGDBAttachment.AttachmentServiceSoap.SetViewSortOrder(Demo.ClientGDBAttachment.SetViewSortOrderRequest request) {
            return base.Channel.SetViewSortOrder(request);
        }
        
        public string SetViewSortOrder(string sessionHandle, string sortExpression) {
            Demo.ClientGDBAttachment.SetViewSortOrderRequest inValue = new Demo.ClientGDBAttachment.SetViewSortOrderRequest();
            inValue.Body = new Demo.ClientGDBAttachment.SetViewSortOrderRequestBody();
            inValue.Body.sessionHandle = sessionHandle;
            inValue.Body.sortExpression = sortExpression;
            Demo.ClientGDBAttachment.SetViewSortOrderResponse retVal = ((Demo.ClientGDBAttachment.AttachmentServiceSoap)(this)).SetViewSortOrder(inValue);
            return retVal.Body.SetViewSortOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.ClientGDBAttachment.GetViewCountResponse Demo.ClientGDBAttachment.AttachmentServiceSoap.GetViewCount(Demo.ClientGDBAttachment.GetViewCountRequest request) {
            return base.Channel.GetViewCount(request);
        }
        
        public string GetViewCount(string sessionHandle, out int recordCount) {
            Demo.ClientGDBAttachment.GetViewCountRequest inValue = new Demo.ClientGDBAttachment.GetViewCountRequest();
            inValue.Body = new Demo.ClientGDBAttachment.GetViewCountRequestBody();
            inValue.Body.sessionHandle = sessionHandle;
            Demo.ClientGDBAttachment.GetViewCountResponse retVal = ((Demo.ClientGDBAttachment.AttachmentServiceSoap)(this)).GetViewCount(inValue);
            recordCount = retVal.Body.recordCount;
            return retVal.Body.GetViewCountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.ClientGDBAttachment.ResetViewFilterResponse Demo.ClientGDBAttachment.AttachmentServiceSoap.ResetViewFilter(Demo.ClientGDBAttachment.ResetViewFilterRequest request) {
            return base.Channel.ResetViewFilter(request);
        }
        
        public string ResetViewFilter(string sessionHandle) {
            Demo.ClientGDBAttachment.ResetViewFilterRequest inValue = new Demo.ClientGDBAttachment.ResetViewFilterRequest();
            inValue.Body = new Demo.ClientGDBAttachment.ResetViewFilterRequestBody();
            inValue.Body.sessionHandle = sessionHandle;
            Demo.ClientGDBAttachment.ResetViewFilterResponse retVal = ((Demo.ClientGDBAttachment.AttachmentServiceSoap)(this)).ResetViewFilter(inValue);
            return retVal.Body.ResetViewFilterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.ClientGDBAttachment.SetViewAdvancedFilterResponse Demo.ClientGDBAttachment.AttachmentServiceSoap.SetViewAdvancedFilter(Demo.ClientGDBAttachment.SetViewAdvancedFilterRequest request) {
            return base.Channel.SetViewAdvancedFilter(request);
        }
        
        public string SetViewAdvancedFilter(string sessionHandle, Demo.ClientGDBAttachment.FilterElement[] filterElements) {
            Demo.ClientGDBAttachment.SetViewAdvancedFilterRequest inValue = new Demo.ClientGDBAttachment.SetViewAdvancedFilterRequest();
            inValue.Body = new Demo.ClientGDBAttachment.SetViewAdvancedFilterRequestBody();
            inValue.Body.sessionHandle = sessionHandle;
            inValue.Body.filterElements = filterElements;
            Demo.ClientGDBAttachment.SetViewAdvancedFilterResponse retVal = ((Demo.ClientGDBAttachment.AttachmentServiceSoap)(this)).SetViewAdvancedFilter(inValue);
            return retVal.Body.SetViewAdvancedFilterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.ClientGDBAttachment.SetViewSearchTextResponse Demo.ClientGDBAttachment.AttachmentServiceSoap.SetViewSearchText(Demo.ClientGDBAttachment.SetViewSearchTextRequest request) {
            return base.Channel.SetViewSearchText(request);
        }
        
        public string SetViewSearchText(string sessionHandle, string searchText) {
            Demo.ClientGDBAttachment.SetViewSearchTextRequest inValue = new Demo.ClientGDBAttachment.SetViewSearchTextRequest();
            inValue.Body = new Demo.ClientGDBAttachment.SetViewSearchTextRequestBody();
            inValue.Body.sessionHandle = sessionHandle;
            inValue.Body.searchText = searchText;
            Demo.ClientGDBAttachment.SetViewSearchTextResponse retVal = ((Demo.ClientGDBAttachment.AttachmentServiceSoap)(this)).SetViewSearchText(inValue);
            return retVal.Body.SetViewSearchTextResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.ClientGDBAttachment.SetViewFacetResponse Demo.ClientGDBAttachment.AttachmentServiceSoap.SetViewFacet(Demo.ClientGDBAttachment.SetViewFacetRequest request) {
            return base.Channel.SetViewFacet(request);
        }
        
        public string SetViewFacet(string sessionHandle, string selectedFacetItem, out Demo.ClientGDBAttachment.Facet[] facets, out int recordCount) {
            Demo.ClientGDBAttachment.SetViewFacetRequest inValue = new Demo.ClientGDBAttachment.SetViewFacetRequest();
            inValue.Body = new Demo.ClientGDBAttachment.SetViewFacetRequestBody();
            inValue.Body.sessionHandle = sessionHandle;
            inValue.Body.selectedFacetItem = selectedFacetItem;
            Demo.ClientGDBAttachment.SetViewFacetResponse retVal = ((Demo.ClientGDBAttachment.AttachmentServiceSoap)(this)).SetViewFacet(inValue);
            facets = retVal.Body.facets;
            recordCount = retVal.Body.recordCount;
            return retVal.Body.SetViewFacetResult;
        }
    }
}
